"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from petstore_client.auth.oauth.oauth2_token_manager import (
    OAuth2TokenManager as OAuth2TokenManager,
)
from petstore_client.auth.oauth.oauth2_client_credentials_authenticator import (
    OAuth2ClientCredentialsAuthenticator as OAuth2ClientCredentialsAuthenticator,
)
from petstore_client.auth.oauth.oauth2_password_authenticator import (
    OAuth2PasswordAuthenticator as OAuth2PasswordAuthenticator,
)
from petstore_client.auth.oauth.oauth2_auth_code_authenticator import (
    OAuth2AuthorizationCodeAuthenticator as OAuth2AuthorizationCodeAuthenticator,
)
from petstore_client.auth.oauth.oauth2_implicit_authenticator import (
    OAuth2ImplicitAuthenticator as OAuth2ImplicitAuthenticator,
)
from petstore_client.auth.oauth.openid_connect_authenticator import (
    OpenIdConnectAuthenticator as OpenIdConnectAuthenticator,
)
