"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from petstore_client.auth.authenticator import Authenticator as Authenticator
from petstore_client.auth.http_aware_authenticator import HttpAwareAuthenticator as HttpAwareAuthenticator
from petstore_client.auth.basic_authenticator import BasicAuthenticator as BasicAuthenticator
from petstore_client.auth.bearer_authenticator import BearerAuthenticator as BearerAuthenticator
from petstore_client.auth.api_key_authenticator import ApiKeyAuthenticator as ApiKeyAuthenticator
from petstore_client.auth.api_key_location import ApiKeyLocation as ApiKeyLocation

__all__ = [
    'Authenticator',
    'HttpAwareAuthenticator',
    'BasicAuthenticator',
    'BearerAuthenticator',
    'ApiKeyAuthenticator',
    'ApiKeyLocation',
]
