"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import base64
from typing import Dict

from .authenticator import Authenticator


class BasicAuthenticator(Authenticator):
    """Authenticator for HTTP Basic authentication."""

    def __init__(self, host: str, username: str, password: str) -> None:
        self._host = host
        credentials = base64.b64encode(f'{username}:{password}'.encode('utf-8')).decode('utf-8')
        self._auth_header = f'Basic {credentials}'

    def get_host(self) -> str:
        return self._host

    def get_auth_headers(self) -> Dict[str, str]:
        return {'Authorization': self._auth_header}
