"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Dict

from .authenticator import Authenticator


class BearerAuthenticator(Authenticator):
    """Authenticator for HTTP Bearer token authentication."""

    def __init__(self, host: str, token: str) -> None:
        self._host = host
        self._token = token

    def get_host(self) -> str:
        return self._host

    def get_auth_headers(self) -> Dict[str, str]:
        return {'Authorization': f'Bearer {self._token}'}
