source 'https://rubygems.org'

gem 'faraday', '~> 2.0'
gem 'oj', '~> 3.0'
gem 'dry-struct', '~> 1.6'
gem 'dry-types', '~> 1.7'

group :development, :test do
  gem 'minitest', '~> 5.0'
  gem 'rake'
  gem 'rubocop', require: false
  gem 'steep', require: false
end
