# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dry-struct', '~> 1.6'
gem 'dry-types', '~> 1.7'
gem 'faraday', '~> 2.0'
gem 'faraday-follow_redirects', '~> 0.3'
gem 'oj', '~> 3.0'

group :development, :test do
  gem 'brotli', '~> 0.5'
  gem 'minitest', '~> 5.0'
  gem 'rake'
  gem 'rubocop', require: false
  gem 'rubocop-minitest', require: false
  gem 'rubocop-rake', require: false
  gem 'steep', require: false
  gem 'testcontainers', '~> 0.2'
  gem 'zstd-ruby', '~> 1.5'
end
