.PHONY: install build test lint format typecheck docs clean

install:
	bundle install --quiet

build: install

test: install
	bundle exec rake test

lint: install
	bundle exec rubocop --format simple --fail-fast

format: install
	bundle exec rubocop -A

typecheck: install
	bundle exec steep check

docs: install
	bundle exec yard doc --output-dir .out/docs --fail-on-warning

clean:
	rm -rf .bundle vendor doc .out .yardoc
