=begin
#Swagger Petstore - OpenAPI 3.0

#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'opigen_client/api_client'
require 'opigen_client/api_error'
require 'opigen_client/version'
require 'opigen_client/configuration'
require 'opigen_client/object_serializer'
require 'opigen_client/header_selector'

# Models
require 'opigen_client/models/api_response'
require 'opigen_client/models/category'
require 'opigen_client/models/order'
require 'opigen_client/models/pet'
require 'opigen_client/models/tag'

# APIs
require 'opigen_client/api/pet_api'
require 'opigen_client/api/store_api'

module OpigenClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpigenClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
