=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

# Dependencies
require 'dry-struct'
require 'dry-types'

# Common files
require 'petstore_client/api_error'
require 'petstore_client/version'
require 'petstore_client/configuration'
require 'petstore_client/header_selector'
require 'petstore_client/object_serializer'
require 'petstore_client/api_response'
require 'petstore_client/api_client'
require 'petstore_client/default_api_client'
require 'petstore_client/api/base_api'

# Models
require 'petstore_client/models/api_response'
require 'petstore_client/models/category'
require 'petstore_client/models/order'
require 'petstore_client/models/pet'
require 'petstore_client/models/tag'

# APIs
require 'petstore_client/api/pet_api'
require 'petstore_client/api/store_api'

module PetstoreClient
  class << self
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
