# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    A simplified Pet Store API for integration testing.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from typing import Any, Dict, List, Optional
from urllib.parse import quote

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from petstore_client.models.pet import Pet

from petstore_client.api_client import ApiClient
from petstore_client.default_api_client import DefaultApiClient
from petstore_client.configuration import Configuration
from petstore_client.base_api import BaseApi


class PetApi(BaseApi):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(
        self,
        api_client: Optional[ApiClient] = None,
        config: Optional[Configuration] = None
    ):
        super().__init__(api_client, config)

    def add_pet(
        self,
        pet: Annotated[Pet, Field(description="Create a new pet in the store")],
    ) -> Pet:
        """Add a new pet to the store

        
        :param pet: Create a new pet in the store (required)
        :return: Pet
        """
        if pet is None:
            raise ValueError("Missing the required parameter 'pet' when calling add_pet")

        path = '/pet'

        query_params: Dict[str, Any] = {}

        header_params: Dict[str, str] = {}

        return self.invoke_api(
            'POST',
            path,
            query_params,
            header_params,
            pet,
            ['application/json'],
            'application/json',
            [],
            'Pet'
        )

    def delete_pet(
        self,
        pet_id: Annotated[StrictInt, Field(description="Pet id to delete")],
    ) -> None:
        """Deletes a pet

        
        :param pet_id: Pet id to delete (required)
        """
        if pet_id is None:
            raise ValueError("Missing the required parameter 'pet_id' when calling delete_pet")

        path = '/pet/{petId}'.replace('{' + 'petId' + '}', quote(str(pet_id), safe=''))

        query_params: Dict[str, Any] = {}

        header_params: Dict[str, str] = {}

        return self.invoke_api(
            'DELETE',
            path,
            query_params,
            header_params,
            None,
            [],
            'application/json',
            [],
            None
        )

    def find_pets_by_status(
        self,
        status: Annotated[Optional[StrictStr], Field(description="Status values that need to be considered for filter")] = None,
    ) -> List[Pet]:
        """Finds Pets by status

        
        :param status: Status values that need to be considered for filter (optional, default to available)
        :return: List[Pet]
        """

        path = '/pet/findByStatus'

        query_params: Dict[str, Any] = {}
        if status is not None:
            query_params['status'] = status

        header_params: Dict[str, str] = {}

        return self.invoke_api(
            'GET',
            path,
            query_params,
            header_params,
            None,
            ['application/json'],
            'application/json',
            [],
            'List[Pet]'
        )

    def get_pet_by_id(
        self,
        pet_id: Annotated[StrictInt, Field(description="ID of pet to return")],
    ) -> Pet:
        """Find pet by ID

        Returns a single pet
        :param pet_id: ID of pet to return (required)
        :return: Pet
        """
        if pet_id is None:
            raise ValueError("Missing the required parameter 'pet_id' when calling get_pet_by_id")

        path = '/pet/{petId}'.replace('{' + 'petId' + '}', quote(str(pet_id), safe=''))

        query_params: Dict[str, Any] = {}

        header_params: Dict[str, str] = {}

        return self.invoke_api(
            'GET',
            path,
            query_params,
            header_params,
            None,
            ['application/json'],
            'application/json',
            [],
            'Pet'
        )

    def update_pet(
        self,
        pet_id: Annotated[StrictInt, Field(description="ID of pet to update")],
        pet: Annotated[Pet, Field(description="Pet object that needs to be updated")],
    ) -> Pet:
        """Update an existing pet

        
        :param pet_id: ID of pet to update (required)
        :param pet: Pet object that needs to be updated (required)
        :return: Pet
        """
        if pet_id is None:
            raise ValueError("Missing the required parameter 'pet_id' when calling update_pet")
        if pet is None:
            raise ValueError("Missing the required parameter 'pet' when calling update_pet")

        path = '/pet/{petId}'.replace('{' + 'petId' + '}', quote(str(pet_id), safe=''))

        query_params: Dict[str, Any] = {}

        header_params: Dict[str, str] = {}

        return self.invoke_api(
            'PUT',
            path,
            query_params,
            header_params,
            pet,
            ['application/json'],
            'application/json',
            [],
            'Pet'
        )
