=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

module OpigenClient
  class ApiClient
    def send_request(method, url, headers, body)
      raise NotImplementedError, "#{self.class}#send_request must be implemented"
    end
  end
end
