=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

module OpigenClient
  # Unified entry point for all API services. Takes an {Auth::Authenticator}
  # and exposes each API group as a typed property.
  class Client
    # @return [OpigenClient::Api::PetApi]
    attr_reader :pet

    # @return [OpigenClient::Api::StoreApi]
    attr_reader :store

    # Creates a new client with the given authenticator.
    # @param authenticator [Auth::Authenticator] Provides host URL and auth headers.
    def initialize(authenticator)
      config = Configuration.default
      config.base_url = authenticator.host
      authenticator.auth_headers.each { |key, value| config.default_headers[key] = value }
      api_client = DefaultApiClient.new(config)
      @pet = Api::PetApi.new(api_client, config)
      @store = Api::StoreApi.new(api_client, config)
    end

    # Creates a client authenticated with a static Bearer token.
    # @param host [String] API base URL.
    # @param access_token [String] Bearer token.
    # @return [Client] Configured client instance.
    def self.with_token(host, access_token)
      auth = Class.new(Auth::Authenticator) do
        define_method(:host) { host }
        define_method(:auth_headers) { { 'Authorization' => "Bearer #{access_token}" } }
      end
      new(auth.new)
    end
  end
end
