=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

module PetstoreClient
  # Configuration for API clients.
  #
  # Holds settings that apply to all API requests such as the base URL,
  # default headers, TLS options, proxy, timeout, and retry policy.
  class Configuration
    # Base URL for all API requests.
    attr_accessor :base_url

    # Headers to include in every API request. Use this for authentication
    # (e.g. Authorization header) and other custom headers.
    # @return [Hash{String => String}]
    attr_accessor :default_headers

    # Enable debug logging of HTTP requests and responses.
    # @return [Boolean]
    attr_accessor :debug

    # Enable SSL/TLS certificate verification.
    # @return [Boolean]
    attr_accessor :verify_ssl

    # Path to a CA certificate file for SSL/TLS verification.
    # @return [String, nil]
    attr_accessor :ssl_ca_cert

    # Path to a client certificate file for mutual TLS authentication.
    # @return [String, nil]
    attr_accessor :cert_file

    # Path to a client private key file for mutual TLS authentication.
    # @return [String, nil]
    attr_accessor :key_file

    # Proxy URL for all API requests.
    # @return [String, nil]
    attr_accessor :proxy

    # Request timeout in seconds. nil means no timeout.
    # @return [Integer, nil]
    attr_accessor :timeout

    # Number of retry attempts for failed requests. nil means no retries.
    # @return [Integer, nil]
    attr_accessor :retries

    def initialize
      @base_url = '/api/v3'
      @default_headers = {}
      @debug = false
      @verify_ssl = true
      @ssl_ca_cert = nil
      @cert_file = nil
      @key_file = nil
      @proxy = nil
      @timeout = nil
      @retries = nil

      yield(self) if block_given?
    end

    # Return the default configuration instance, creating it lazily if needed.
    def self.default
      @@default ||= Configuration.new
    end

    # Set the default configuration instance.
    def self.default=(configuration)
      @@default = configuration
    end
  end
end
