=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

require 'faraday'

module OpigenClient
  class DefaultApiClient < ApiClient
    def initialize(config = nil)
      super()
      @config = config
    end

    def send_request(method, url, headers, body)
      conn = Faraday.new do |f|
        if @config
          f.proxy = @config.proxy if @config.proxy
          f.ssl.verify = @config.verify_ssl
          f.ssl.ca_file = @config.ssl_ca_cert if @config.ssl_ca_cert
          f.ssl.client_cert = @config.cert_file if @config.cert_file
          f.ssl.client_key = @config.key_file if @config.key_file
        end
      end

      response = conn.run_request(method.downcase.to_sym, url, body, headers)

      ApiResponse.new(
        status_code: response.status,
        body: response.body,
        headers: response.headers.to_h
      )
    end
  end
end
