=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

require 'typhoeus'

module PetstoreClient
  class DefaultApiClient < ApiClient
    def initialize(config = nil)
      @config = config
    end

    def send_request(method, url, headers, body)
      options = {
        method: method,
        headers: headers,
        body: body
      }

      if @config
        options[:proxy] = @config.proxy if @config.proxy
        options[:ssl_verifypeer] = @config.verify_ssl
        options[:ssl_verifyhost] = @config.verify_ssl ? 2 : 0
        options[:cainfo] = @config.ssl_ca_cert if @config.ssl_ca_cert
      end

      request = Typhoeus::Request.new(url, options)
      response = request.run

      ApiResponse.new(
        status_code: response.code,
        body: response.body,
        headers: response.headers ? response.headers.to_h : {}
      )
    end
  end
end
