=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

require 'typhoeus'

module OpigenClient
  class DefaultApiClient < ApiClient
    def send_request(method, url, headers, body)
      request = Typhoeus::Request.new(
        url,
        method: method,
        headers: headers,
        body: body
      )

      response = request.run

      ApiResponse.new(
        status_code: response.code,
        body: response.body,
        headers: response.headers ? response.headers.to_h : {}
      )
    end
  end
end
