=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

require 'date'
require 'json'
require 'time'

module OpigenClient
  # Exception raised when serialization or deserialization fails.
  class SerializationError < StandardError
    attr_reader :cause

    def initialize(message, cause = nil)
      super(message)
      @cause = cause
    end
  end

  # Handles JSON serialization and deserialization for API requests and responses.
  #
  # All serde operations in the generated client route through this class.
  # The parameter encoding methods provide consistent value conversion for
  # URL path, query string, header, and form parameters.
  class ObjectSerializer
    DEFAULT_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S%z'.freeze

    # Serialize an object to a JSON string.
    def self.serialize(object)
      sanitized = sanitize_for_serialization(object)
      JSON.generate(sanitized)
    rescue => e
      raise SerializationError.new("Failed to serialize object to JSON: #{e.message}", e)
    end

    # Deserialize a JSON string to an object of the specified type.
    def self.deserialize(json_string, target_type)
      return nil if json_string.nil? || (json_string.is_a?(String) && json_string.empty?)

      data = if json_string.is_a?(String)
               JSON.parse(json_string, symbolize_names: true)
             else
               json_string
             end

      convert_to_type(data, target_type)
    rescue JSON::ParserError => e
      raise SerializationError.new("Failed to parse JSON: #{e.message}", e)
    rescue => e
      raise e if e.is_a?(SerializationError)

      raise SerializationError.new("Failed to deserialize JSON to #{target_type}: #{e.message}", e)
    end

    # Convert a value to a string suitable for use as a URL path parameter.
    def self.to_path_value(value)
      return '' if value.nil?
      return value ? 'true' : 'false' if value.is_a?(TrueClass) || value.is_a?(FalseClass)
      return value.strftime(DEFAULT_DATETIME_FORMAT) if value.is_a?(Time) || value.is_a?(DateTime)
      return value.to_s if value.is_a?(Date)

      value.to_s
    end

    # Convert a value to a representation suitable for use as a query parameter.
    # For collections, joins using the specified collection format delimiter.
    def self.to_query_value(value, collection_format = nil)
      return nil if value.nil?

      if value.is_a?(Array)
        items = value.map(&:to_s)
        case collection_format
        when :ssv then items.join(' ')
        when :tsv then items.join("\t")
        when :pipes then items.join('|')
        when :multi then items
        else items.join(',')
        end
      elsif value.is_a?(TrueClass) || value.is_a?(FalseClass)
        value ? 'true' : 'false'
      elsif value.is_a?(Time) || value.is_a?(DateTime)
        value.strftime(DEFAULT_DATETIME_FORMAT)
      elsif value.is_a?(Date)
        value.to_s
      else
        value.to_s
      end
    end

    # Convert a value to a string suitable for use as an HTTP header value.
    def self.to_header_value(value)
      return '' if value.nil?

      if value.is_a?(Array)
        value.map(&:to_s).join(',')
      elsif value.is_a?(TrueClass) || value.is_a?(FalseClass)
        value ? 'true' : 'false'
      elsif value.is_a?(Time) || value.is_a?(DateTime)
        value.strftime(DEFAULT_DATETIME_FORMAT)
      elsif value.is_a?(Date)
        value.to_s
      else
        value.to_s
      end
    end

    # Convert a value to a representation suitable for use as a form parameter.
    def self.to_form_value(value)
      return '' if value.nil?

      if value.is_a?(TrueClass) || value.is_a?(FalseClass)
        value ? 'true' : 'false'
      elsif value.is_a?(Time) || value.is_a?(DateTime)
        value.strftime(DEFAULT_DATETIME_FORMAT)
      elsif value.is_a?(Date)
        value.to_s
      else
        value.to_s
      end
    end

    def self.sanitize_for_serialization(object)
      case object
      when nil
        nil
      when String, Integer, Float, TrueClass, FalseClass
        object
      when Array
        object.map { |item| sanitize_for_serialization(item) }
      when Hash
        object.each_with_object({}) do |(key, value), hash|
          hash[key] = sanitize_for_serialization(value)
        end
      when Date
        object.to_s
      when Time, DateTime
        object.strftime(DEFAULT_DATETIME_FORMAT)
      else
        if object.class.respond_to?(:attribute_map)
          hash = {}
          object.class.attribute_map.each do |attr, json_key|
            value = object.send(attr)
            next if value.nil?

            hash[json_key] = sanitize_for_serialization(value)
          end
          hash
        elsif object.respond_to?(:to_hash)
          sanitize_for_serialization(object.to_hash)
        elsif object.respond_to?(:to_json)
          object
        else
          object.to_s
        end
      end
    end

    def self.convert_to_type(data, return_type)
      return nil if data.nil?

      case return_type
      when 'String'
        data.to_s
      when 'Integer'
        data.to_i
      when 'Float'
        data.to_f
      when 'Boolean'
        data == true
      when 'Time'
        Time.parse(data.to_s)
      when 'Date'
        Date.parse(data.to_s)
      when 'Object'
        data
      when /\AArray<(.+)>\z/
        sub_type = $1
        data.map { |item| convert_to_type(item, sub_type) }
      when /\AHash<String,\s*(.+)>\z/
        sub_type = $1
        data.each_with_object({}) do |(key, value), hash|
          hash[key] = convert_to_type(value, sub_type)
        end
      else
        klass = begin
          OpigenClient::Models.const_get(return_type)
        rescue NameError
          OpigenClient.const_get(return_type)
        end
        if klass.respond_to?(:openapi_one_of)
          klass.build(data)
        elsif klass.respond_to?(:build_from_hash)
          klass.build_from_hash(data)
        else
          klass.new(data)
        end
      end
    end

    private_class_method :sanitize_for_serialization
  end
end
