"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Dict, List

from ..authenticator import Authenticator
from .oauth2_token_manager import OAuth2TokenManager


class OAuth2ClientCredentialsAuthenticator(Authenticator):
    """Authenticator for OAuth2 client credentials flow."""

    def __init__(
        self,
        host: str,
        client_id: str,
        client_secret: str,
        token_url: str,
        scopes: List[str],
    ) -> None:
        self._host = host
        self._client_id = client_id
        self._client_secret = client_secret
        self._token_url = token_url
        self._scopes = list(scopes)
        self._token_manager = OAuth2TokenManager()

    def get_host(self) -> str:
        return self._host

    def get_auth_headers(self) -> Dict[str, str]:
        params = {
            'grant_type': 'client_credentials',
            'client_id': self._client_id,
            'client_secret': self._client_secret,
        }
        if self._scopes:
            params['scope'] = ' '.join(self._scopes)
        token = self._token_manager.get_access_token(self._token_url, params)
        return {'Authorization': f'Bearer {token}'}
