"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
from typing import Dict, Optional, Sequence

from ...api_client import ApiClient
from ..http_aware_authenticator import HttpAwareAuthenticator
from .oauth2_auth_code_authenticator import OAuth2AuthorizationCodeAuthenticator


class OpenIdConnectAuthenticator(HttpAwareAuthenticator):
    """Authenticator for OpenID Connect.

    Fetches the OIDC discovery document to discover the authorization and
    token endpoints, then delegates to an
    :class:`OAuth2AuthorizationCodeAuthenticator`.

    Implements :class:`HttpAwareAuthenticator` so that both the discovery
    request and subsequent token exchange requests use the shared
    :class:`ApiClient` with the same transport configuration (proxy, TLS,
    timeouts) as regular API calls.
    """

    def __init__(
        self,
        host: str,
        openid_connect_url: str,
        client_id: str,
        client_secret: str,
        redirect_uri: str,
        scopes: Sequence[str],
    ) -> None:
        """Create a new OpenID Connect authenticator.

        Args:
            host: API base URL.
            openid_connect_url: OIDC discovery document URL.
            client_id: OAuth2 client ID.
            client_secret: OAuth2 client secret.
            redirect_uri: Redirect URI registered with the provider.
            scopes: Requested scopes.
        """
        self._host = host
        self._openid_connect_url = openid_connect_url
        self._client_id = client_id
        self._client_secret = client_secret
        self._redirect_uri = redirect_uri
        self._scopes = tuple(scopes)
        self._api_client: Optional[ApiClient] = None
        self._delegate: Optional[OAuth2AuthorizationCodeAuthenticator] = None

    def set_api_client(self, api_client: ApiClient) -> None:
        """Inject the shared API client for making HTTP requests.

        Args:
            api_client: The shared API client instance.
        """
        self._api_client = api_client

    def _get_delegate(self) -> OAuth2AuthorizationCodeAuthenticator:
        """Lazily discover the OIDC endpoints and create the delegate.

        Returns:
            The authorization code authenticator delegate.

        Raises:
            RuntimeError: If no API client has been injected or the
                discovery request fails.
        """
        if self._delegate is None:
            if self._api_client is None:
                raise RuntimeError(
                    'ApiClient has not been injected. '
                    'Ensure the Client constructor calls set_api_client() '
                    'on HttpAwareAuthenticator before making API requests.'
                )
            headers: Dict[str, str] = {'Accept': 'application/json'}
            response = self._api_client.send_request('GET', self._openid_connect_url, headers, None)
            discovery = json.loads(response.body)
            authorization_endpoint = discovery['authorization_endpoint']
            token_endpoint = discovery['token_endpoint']
            self._delegate = OAuth2AuthorizationCodeAuthenticator(
                self._host,
                self._client_id,
                self._client_secret,
                authorization_endpoint,
                token_endpoint,
                self._redirect_uri,
                self._scopes,
            )
            self._delegate.set_api_client(self._api_client)
        return self._delegate

    def build_authorization_url(self, state: Optional[str] = None) -> str:
        """Build the authorization URL using the discovered authorization endpoint.

        Args:
            state: CSRF state parameter.

        Returns:
            The authorization URL.
        """
        return self._get_delegate().build_authorization_url(state)

    def exchange_code(self, code: str) -> None:
        """Exchange an authorization code for tokens using the discovered token endpoint.

        Args:
            code: The authorization code from the callback.
        """
        self._get_delegate().exchange_code(code)

    def get_host(self) -> str:
        """Returns the base URL of the API."""
        return self._host

    def get_auth_headers(self) -> Dict[str, str]:
        """Returns the authentication headers from the delegate.

        Returns:
            Dict with the Authorization header.
        """
        return self._get_delegate().get_auth_headers()
