"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
from typing import Dict, List, Optional
from urllib.request import urlopen

from ..authenticator import Authenticator
from .oauth2_auth_code_authenticator import OAuth2AuthorizationCodeAuthenticator


class OpenIdConnectAuthenticator(Authenticator):
    """Authenticator for OpenID Connect."""

    def __init__(
        self,
        host: str,
        openid_connect_url: str,
        client_id: str,
        client_secret: str,
        redirect_uri: str,
        scopes: List[str],
    ) -> None:
        self._host = host
        self._openid_connect_url = openid_connect_url
        self._client_id = client_id
        self._client_secret = client_secret
        self._redirect_uri = redirect_uri
        self._scopes = list(scopes)
        self._delegate: Optional[OAuth2AuthorizationCodeAuthenticator] = None

    def _get_delegate(self) -> OAuth2AuthorizationCodeAuthenticator:
        if self._delegate is None:
            with urlopen(self._openid_connect_url) as resp:
                discovery = json.loads(resp.read().decode('utf-8'))
            self._delegate = OAuth2AuthorizationCodeAuthenticator(
                self._host,
                self._client_id,
                self._client_secret,
                discovery['authorization_endpoint'],
                discovery['token_endpoint'],
                self._redirect_uri,
                self._scopes,
            )
        return self._delegate

    def build_authorization_url(self, state: Optional[str] = None) -> str:
        return self._get_delegate().build_authorization_url(state)

    def exchange_code(self, code: str) -> None:
        self._get_delegate().exchange_code(code)

    def get_host(self) -> str:
        return self._host

    def get_auth_headers(self) -> Dict[str, str]:
        return self._get_delegate().get_auth_headers()
