# coding: utf-8

# flake8: noqa
"""
    Swagger Petstore - OpenAPI 3.0

    A simplified Pet Store API for integration testing.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from petstore_client.models.api_response import ApiResponse
from petstore_client.models.category import Category
from petstore_client.models.order import Order
from petstore_client.models.pet import Pet
from petstore_client.models.tag import Tag
