"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class Order(BaseModel):
    """
    Order
    """

    id: Optional[int] = Field(default=None, alias='id')
    pet_id: Optional[int] = Field(default=None, alias='petId')
    quantity: Optional[int] = Field(default=None, alias='quantity')
    ship_date: Optional[datetime] = Field(default=None, alias='shipDate')
    status: Optional[str] = Field(default=None, alias='status')
    complete: Optional[bool] = Field(default=None, alias='complete')
    additional_properties: Dict[str, Any] = {}

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['placed', 'approved', 'delivered']):
            raise ValueError("must be one of enum values ('placed', 'approved', 'delivered')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from datetime import datetime

Order.model_rebuild(raise_errors=False)
