"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class PetFood(BaseModel):
    """
    Food for pets, discriminated by foodType
    """

    one_of_0: Optional[DryFood] = None
    one_of_1: Optional[WetFood] = None
    actual_instance: Optional[Union[DryFood, WetFood]] = None
    one_of_schemas: Set[str] = {'DryFood', 'WetFood'}

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: Dict[str, str] = {
        'dry': 'DryFood',
        'wet': 'WetFood',
        'DryFood': 'DryFood',
        'WetFood': 'WetFood',
    }

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        if args:
            if len(args) > 1:
                raise ValueError('If a position argument is used, only 1 is allowed to set `actual_instance`')
            if kwargs:
                raise ValueError('If a position argument is used, keyword arguments cannot be used.')
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v: Any) -> Any:
        instance = PetFood.model_construct()
        error_messages = []
        match = 0
        if not isinstance(v, DryFood):
            error_messages.append(f'Error! Input type `{type(v)}` is not `DryFood`')
        else:
            match += 1
        if not isinstance(v, WetFood):
            error_messages.append(f'Error! Input type `{type(v)}` is not `WetFood`')
        else:
            match += 1
        if match > 1:
            raise ValueError(
                'Multiple matches found when setting `actual_instance` in PetFood with oneOf schemas: DryFood, WetFood. Details: '
                + ', '.join(error_messages)
            )
        elif match == 0:
            raise ValueError(
                'No match found when setting `actual_instance` in PetFood with oneOf schemas: DryFood, WetFood. Details: '
                + ', '.join(error_messages)
            )
        else:
            return v


from petstore_client.models.dry_food import DryFood
from petstore_client.models.wet_food import WetFood

PetFood.model_rebuild(raise_errors=False)
