"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class Tag(BaseModel):
    """
    Tag
    """

    id: Optional[int] = Field(default=None, alias='id')
    name: Optional[str] = Field(default=None, alias='name')
    additional_properties: Dict[str, Any] = {}

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


Tag.model_rebuild(raise_errors=False)
