<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Auth\OAuth;

use PetstoreClient\Auth\BaseAuthenticator;

class OAuth2ClientCredentialsAuthenticator extends BaseAuthenticator
{
    private readonly string $host;
    private readonly string $clientId;
    private readonly string $clientSecret;
    private readonly string $tokenUrl;
    /** @var string[] */
    private readonly array $scopes;
    private readonly OAuth2TokenManager $tokenManager;

    /** @param string[] $scopes */
    public function __construct(string $host, string $clientId, string $clientSecret, string $tokenUrl, array $scopes)
    {
        $this->host = $host;
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
        $this->tokenUrl = $tokenUrl;
        $this->scopes = $scopes;
        $this->tokenManager = new OAuth2TokenManager();
    }

    public function getHost(): string
    {
        return $this->host;
    }

    /** @return array<string, string> */
    public function getAuthHeaders(): array
    {
        $params = [
            'grant_type' => 'client_credentials',
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
        ];
        if ($this->scopes !== []) {
            $params['scope'] = implode(' ', $this->scopes);
        }
        $token = $this->tokenManager->getAccessToken($this->tokenUrl, $params);
        return ['Authorization' => 'Bearer ' . $token];
    }
}
