<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Auth\OAuth;

use PetstoreClient\Auth\BaseAuthenticator;

class OAuth2AuthorizationCodeAuthenticator extends BaseAuthenticator
{
    private readonly string $host;
    private readonly string $clientId;
    private readonly string $clientSecret;
    private readonly string $authorizationUrl;
    private readonly string $tokenUrl;
    private readonly string $redirectUri;
    /** @var string[] */
    private readonly array $scopes;
    private readonly OAuth2TokenManager $tokenManager;
    private bool $tokenExchanged = false;

    /** @param string[] $scopes */
    public function __construct(
        string $host,
        string $clientId,
        string $clientSecret,
        string $authorizationUrl,
        string $tokenUrl,
        string $redirectUri,
        array $scopes
    ) {
        $this->host = $host;
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
        $this->authorizationUrl = $authorizationUrl;
        $this->tokenUrl = $tokenUrl;
        $this->redirectUri = $redirectUri;
        $this->scopes = $scopes;
        $this->tokenManager = new OAuth2TokenManager();
    }

    public function buildAuthorizationUrl(?string $state = null): string
    {
        $params = [
            'response_type' => 'code',
            'client_id' => $this->clientId,
            'redirect_uri' => $this->redirectUri,
        ];
        if ($this->scopes !== []) {
            $params['scope'] = implode(' ', $this->scopes);
        }
        if ($state !== null) {
            $params['state'] = $state;
        }
        return $this->authorizationUrl . '?' . http_build_query($params);
    }

    public function exchangeCode(string $code): void
    {
        $params = [
            'grant_type' => 'authorization_code',
            'code' => $code,
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri' => $this->redirectUri,
        ];
        $this->tokenManager->getAccessToken($this->tokenUrl, $params);
        $this->tokenExchanged = true;
    }

    public function getHost(): string
    {
        return $this->host;
    }

    /** @return array<string, string> */
    public function getAuthHeaders(): array
    {
        if (!$this->tokenExchanged) {
            throw new \RuntimeException('Must call exchangeCode() before making API requests');
        }
        $params = ['grant_type' => 'refresh_token'];
        $token = $this->tokenManager->getAccessToken($this->tokenUrl, $params);
        return ['Authorization' => 'Bearer ' . $token];
    }
}
