.PHONY: build test lint format analyze docs clean upgrade checkstyle

build:
	mvn compile -q -B

test:
	mvn test -q -B

lint:
	mvn checkstyle:check spotbugs:check -q -B

checkstyle:
	mvn checkstyle:check -q -B

format:
	mvn spotless:apply -q -B

analyze:
	mvn compile spotbugs:check -q -B

upgrade:
	mvn rewrite:run -q -B

docs:
	mvn javadoc:javadoc -q -B

clean:
	mvn clean -q -B
