.PHONY: install build test lint format docs clean

install:
	mix deps.get

build: install
	mix compile

test: install
	mix test

lint: install
	mix format --check-formatted

format: install
	mix format

docs: install
	mix docs

clean:
	mix clean
	rm -rf _build deps doc
