# frozen_string_literal: true

# Swagger Petstore - OpenAPI 3.0
# A simplified Pet Store API for integration testing.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

module PetstoreClient
  # Unified entry point for all API services. Takes an {Auth::Authenticator}
  # and exposes each API group as a typed property.
  class Client
    # @return [PetstoreClient::Api::PetApi]
    attr_reader :pet

    # @return [PetstoreClient::Api::StoreApi]
    attr_reader :store

    # Creates a new client with the given authenticator.
    # @param authenticator [Auth::Authenticator] Provides host URL and auth headers.
    def initialize(authenticator)
      config = Configuration.default
      config.base_url = authenticator.host
      authenticator.auth_headers.each { |key, value| config.default_headers[key] = value }
      api_client = DefaultApiClient.new(config)
      @pet = Api::PetApi.new(api_client, config)
      @store = Api::StoreApi.new(api_client, config)
    end

    # Creates a client authenticated with a static Bearer token.
    # @param host [String] API base URL.
    # @param access_token [String] Bearer token.
    # @return [Client] Configured client instance.
    def self.with_token(host, access_token)
      new(Auth::BearerAuthenticator.new(host, access_token))
    end
  end
end
