# frozen_string_literal: true

# Swagger Petstore - OpenAPI 3.0
# A simplified Pet Store API for integration testing.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'faraday'
require 'json'
require 'securerandom'

module PetstoreClient
  # Default HTTP client implementation backed by Faraday.
  class DefaultApiClient < ApiClient
    def initialize(config = nil)
      super()
      @config = config
    end

    def send_request(method, url, headers, body) # rubocop:disable Metrics/MethodLength
      if body.is_a?(Hash)
        boundary = SecureRandom.uuid
        headers['Content-Type'] = "multipart/form-data; boundary=#{boundary}"
        serialized_body = build_multipart_body(body, boundary)
      else
        serialized_body = body
      end

      conn = build_connection
      response = conn.run_request(method.downcase.to_sym, url, serialized_body, headers)

      ApiResponse.new(
        status_code: response.status,
        body: response.body,
        headers: response.headers.to_h
      )
    end

    private

    def build_connection # rubocop:disable Metrics/AbcSize
      Faraday.new do |f|
        if @config
          f.proxy = @config.proxy if @config.proxy
          f.ssl.verify = @config.verify_ssl
          f.ssl.ca_file = @config.ssl_ca_cert if @config.ssl_ca_cert
          f.ssl.client_cert = @config.cert_file if @config.cert_file
          f.ssl.client_key = @config.key_file if @config.key_file
        end
      end
    end

    def build_multipart_body(form_parts, boundary)
      # @type var parts: Array[String]
      parts = []
      form_parts.each do |name, value|
        if value.is_a?(Array)
          value.each { |item| parts << multipart_part(name, item, boundary) }
        else
          parts << multipart_part(name, value, boundary)
        end
      end
      parts.join + "--#{boundary}--\r\n"
    end

    def multipart_part(name, value, boundary)
      if value.respond_to?(:read)
        "--#{boundary}\r\nContent-Disposition: form-data; name=\"#{name}\"; filename=\"#{name}\"\r\n" \
          "Content-Type: application/octet-stream\r\n\r\n#{value.read}\r\n"
      elsif value.respond_to?(:to_hash)
        json_str = JSON.generate(value.to_hash)
        "--#{boundary}\r\nContent-Disposition: form-data; name=\"#{name}\"\r\n" \
          "Content-Type: application/json\r\n\r\n#{json_str}\r\n"
      else
        "--#{boundary}\r\nContent-Disposition: form-data; name=\"#{name}\"\r\n\r\n#{value}\r\n"
      end
    end
  end
end
