<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Models;

/**
 * Food for pets, discriminated by foodType
 */
class PetFood
{
    private const ONE_OF_SCHEMAS = ['DryFood', 'WetFood'];

    private const DISCRIMINATOR_PROPERTY = 'foodType';

    private const DISCRIMINATOR_MAPPING = [
        'dry' => DryFood::class,
        'wet' => WetFood::class
    ];

    private mixed $actualInstance;

    public function __construct(mixed $actualInstance = null)
    {
        $this->actualInstance = $actualInstance;
    }

    public function getActualInstance(): mixed
    {
        return $this->actualInstance;
    }

    public static function build(mixed $data): self
    {
        if (is_array($data) && isset($data[self::DISCRIMINATOR_PROPERTY])) {
            $class = self::DISCRIMINATOR_MAPPING[$data[self::DISCRIMINATOR_PROPERTY]] ?? null;
            if ($class !== null) {
                return new self(\PetstoreClient\ObjectSerializer::deserialize($data, $class));
            }
        }

        return new self($data);
    }
}
