<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class Tag
{
    #[SerializedName('id')]
    public ?int $id = null;

    #[SerializedName('name')]
    public ?string $name = null;

    public function __construct(
        ?int $id = null,
        ?string $name = null,
    ) {
        $this->id = $id;
        $this->name = $name;
    }
}
