<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class WetFood
{
    #[SerializedName('foodType')]
    public string $foodType;

    #[SerializedName('volumeMl')]
    public int $volumeMl;

    /**
     */
    public function __construct(
        string $foodType,
        int $volumeMl,
    ) {
        $this->foodType = $foodType;
        $this->volumeMl = $volumeMl;
    }
}
