module PetstoreClient
  module Api
    class PetApi < BaseApi
      def initialize: (?::PetstoreClient::ApiClient? api_client, ?::PetstoreClient::Configuration config) -> void
      def add_pet: (::PetstoreClient::Auth::Authenticator auth, Models::Pet pet) -> untyped
      def add_pet_photos: (Integer pet_id, Array[File] files, Models::PhotoMetadata metadata) -> untyped
      def delete_pet: (::PetstoreClient::Auth::Authenticator auth, Integer pet_id) -> untyped
      def download_pet_document: (Integer pet_id, Integer document_id) -> untyped
      def find_pets_by_status: (?Hash[Symbol, untyped] opts) -> untyped
      def get_pet_avatar: (Integer pet_id) -> untyped
      def get_pet_avatar_thumbnail: (Integer pet_id) -> untyped
      def get_pet_by_id: (Integer pet_id) -> untyped
      def get_pet_passport: (Integer pet_id) -> untyped
      def get_pet_photo: (Integer pet_id, Integer photo_id) -> untyped
      def set_pet_avatar: (Integer pet_id, File body) -> untyped
      def set_pet_avatar_thumbnail: (Integer pet_id, Models::SetPetAvatarThumbnailRequest set_pet_avatar_thumbnail_request) -> untyped
      def update_pet: (Integer pet_id, Models::Pet pet) -> untyped
      def upload_pet_certificate: (Integer pet_id, File file) -> untyped
      def upload_pet_document: (Integer pet_id, File file, ?Hash[Symbol, untyped] opts) -> untyped
    end
  end
end
