=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

module OpigenClient
  module Auth
    # Base class for providing authentication credentials to the API client.
    # Subclasses supply the API host URL and authorization headers.
    class Authenticator
      # Returns the base URL of the API.
      # @return [String]
      def host
        raise NotImplementedError, "#{self.class}#host must be implemented"
      end

      # Returns the authentication headers to include in every request.
      # @return [Hash{String => String}]
      def auth_headers
        raise NotImplementedError, "#{self.class}#auth_headers must be implemented"
      end
    end
  end
end
