# coding: utf-8

# flake8: noqa

"""
    Swagger Petstore - OpenAPI 3.0

    A simplified Pet Store API for integration testing.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "PetApi",
    "StoreApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "ObjectSerializer",
    "SerializationError",
    "HeaderSelector",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiResponse",
    "Category",
    "Order",
    "Pet",
    "Tag",
]

# import apis into sdk package
from petstore_client.api.pet_api import PetApi as PetApi
from petstore_client.api.store_api import StoreApi as StoreApi

# import ApiClient
from petstore_client.api_response import ApiResponse as ApiResponse
from petstore_client.api_client import ApiClient as ApiClient
from petstore_client.configuration import Configuration as Configuration
from petstore_client.object_serializer import ObjectSerializer as ObjectSerializer
from petstore_client.object_serializer import SerializationError as SerializationError
from petstore_client.header_selector import HeaderSelector as HeaderSelector
from petstore_client.exceptions import OpenApiException as OpenApiException
from petstore_client.exceptions import ApiTypeError as ApiTypeError
from petstore_client.exceptions import ApiValueError as ApiValueError
from petstore_client.exceptions import ApiKeyError as ApiKeyError
from petstore_client.exceptions import ApiAttributeError as ApiAttributeError
from petstore_client.exceptions import ApiException as ApiException

# import models into sdk package
from petstore_client.models.api_response import ApiResponse as ApiResponse
from petstore_client.models.category import Category as Category
from petstore_client.models.order import Order as Order
from petstore_client.models.pet import Pet as Pet
from petstore_client.models.tag import Tag as Tag
