"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from petstore_client.auth.authenticator import Authenticator
from petstore_client.configuration import Configuration
from petstore_client.default_api_client import DefaultApiClient
from petstore_client.api.pet_api import PetApi
from petstore_client.api.store_api import StoreApi


class Client:
    """Unified entry point for all API services.

    Takes an :class:`Authenticator` and exposes each API group as a typed
    property.
    """

    def __init__(self, authenticator: Authenticator) -> None:
        """Creates a new client with the given authenticator.

        Args:
            authenticator: Provides host URL and auth headers.
        """
        config = Configuration()
        config.base_url = authenticator.get_host()
        config.default_headers.update(authenticator.get_auth_headers())
        api_client = DefaultApiClient(config)
        self.pet: PetApi = PetApi(api_client, config)
        self.store: StoreApi = StoreApi(api_client, config)
