# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    A simplified Pet Store API for integration testing.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from typing import Dict, Optional

import urllib3

from petstore_client.api_client import ApiClient
from petstore_client.api_response import ApiResponse


class DefaultApiClient:
    """Default implementation of ApiClient using urllib3."""

    def __init__(self, pool_manager: Optional[urllib3.PoolManager] = None):
        self._pool_manager = pool_manager or urllib3.PoolManager()

    def send_request(
        self,
        method: str,
        url: str,
        headers: Dict[str, str],
        body: Optional[str]
    ) -> ApiResponse:
        """Send an HTTP request and return the response.

        :param method: HTTP method (GET, POST, PUT, DELETE, etc.)
        :param url: Fully qualified URL
        :param headers: HTTP headers
        :param body: Request body (serialized JSON string, or None)
        :return: ApiResponse containing status code, body, and headers
        """
        response = self._pool_manager.request(
            method,
            url,
            headers=headers,
            body=body.encode('utf-8') if body else None
        )

        response_body = response.data.decode('utf-8') if response.data else ''
        response_headers = dict(response.headers) if response.headers else {}

        return ApiResponse(
            status_code=response.status,
            body=response_body,
            headers=response_headers
        )
