<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class Pet
{
    public const STATUS_AVAILABLE = 'available';
    public const STATUS_PENDING = 'pending';
    public const STATUS_SOLD = 'sold';

    #[SerializedName('id')]
    public ?int $id = null;

    #[SerializedName('name')]
    public string $name;

    #[SerializedName('category')]
    public ?\PetstoreClient\Models\Category $category = null;

    /** @var string[] */
    #[SerializedName('photoUrls')]
    public array $photoUrls;

    /** @var \PetstoreClient\Models\Tag[]|null */
    #[SerializedName('tags')]
    public ?array $tags = null;

    /**
     * pet status in the store
     */
    #[SerializedName('status')]
    public ?string $status = null;

    /**
     * @param string[] $photoUrls
     * @param \PetstoreClient\Models\Tag[]|null $tags
     */
    public function __construct(
        string $name,
        array $photoUrls,
        ?int $id = null,
        ?\PetstoreClient\Models\Category $category = null,
        ?array $tags = null,
        ?string $status = null,
    ) {
        $this->id = $id;
        $this->name = $name;
        $this->category = $category;
        $this->photoUrls = $photoUrls;
        $this->tags = $tags;
        $this->status = $status;
    }
}
