.PHONY: all build test format lint clean

all: build

build:
	swift build

test:
	swift test

format:
	swift format --recursive --in-place Sources Tests

lint:
	swift format --recursive --check Sources Tests

clean:
	swift package clean
