=begin
#Swagger Petstore - OpenAPI 3.0

#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'
require 'dry-struct'

module Types
  include Dry.Types()
end

module OpigenClient::Models
  class ApiResponse < Dry::Struct
    # Attribute mapping from ruby-style variable name to JSON key.
    ATTRIBUTE_MAP = {
      code: :'code',
      type: :'type',
      message: :'message'
    }.freeze

    # Inverse mapping from JSON key to ruby attribute name.
    JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

    # Attribute type mapping.
    def self.openapi_types
      {
        :'code' => :'Integer',
        :'type' => :'String',
        :'message' => :'String'
      }
    end

    def self.attribute_map
      ATTRIBUTE_MAP
    end

    # Transform incoming hash keys from JSON format to Ruby attribute names.
    transform_keys do |key|
      JSON_KEY_MAP[key.to_sym] || key.to_sym
    end

    attribute :code, Types::Any.optional.meta(omittable: true)
    attribute :type, Types::Any.optional.meta(omittable: true)
    attribute :message, Types::Any.optional.meta(omittable: true)

    # Builds the object from a JSON-keyed hash, recursively deserializing nested types.
    # @param [Hash] attributes JSON-keyed hash
    # @return [ApiResponse] Deserialized object
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      attributes = attributes.transform_keys(&:to_sym)
      transformed = {}
      openapi_types.each do |attr, type|
        json_key = ATTRIBUTE_MAP[attr]
        next unless attributes.key?(json_key)

        value = attributes[json_key]
        if value.nil?
          transformed[attr] = nil
        else
          transformed[attr] = OpigenClient::ObjectSerializer.convert_to_type(value, type.to_s)
        end
      end
      new(transformed)
    end
  end
end
