=begin
#Swagger Petstore - OpenAPI 3.0

#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'
require 'dry-struct'

module Types
  include Dry.Types()
end

module PetstoreClient::Models
  class Category < Dry::Struct
    # Attribute mapping from ruby-style variable name to JSON key.
    ATTRIBUTE_MAP = {
      id: :'id',
      name: :'name'
    }.freeze

    # Inverse mapping from JSON key to ruby attribute name.
    JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

    # Attribute type mapping.
    OPENAPI_TYPES = {
      :'id' => :'Integer',
      :'name' => :'String'
    }.freeze

    # Transform incoming hash keys from JSON format to Ruby attribute names.
    transform_keys do |key|
      JSON_KEY_MAP[key.to_sym] || key.to_sym
    end

    attribute :id, Types::Any.optional.meta(omittable: true)
    attribute :name, Types::Any.optional.meta(omittable: true)
  end
end
