=begin
#Swagger Petstore - OpenAPI 3.0

#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'
require 'dry-struct'

module Types
  include Dry.Types()
end

module PetstoreClient::Models
  class DryFood < Dry::Struct
    # Attribute mapping from ruby-style variable name to JSON key.
    ATTRIBUTE_MAP = {
      food_type: :'foodType',
      weight_kg: :'weightKg'
    }.freeze

    # Inverse mapping from JSON key to ruby attribute name.
    JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

    # Attribute type mapping.
    OPENAPI_TYPES = {
      :'food_type' => :'String',
      :'weight_kg' => :'Float'
    }.freeze

    # Transform incoming hash keys from JSON format to Ruby attribute names.
    transform_keys do |key|
      JSON_KEY_MAP[key.to_sym] || key.to_sym
    end

    attribute :food_type, Types::Any
    attribute :weight_kg, Types::Any
  end
end
