module OpigenClient::Models
  class Order < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    attr_reader id: Integer?
    attr_reader pet_id: Integer?
    attr_reader quantity: Integer?
    attr_reader ship_date: Time?
    attr_reader status: String?
    attr_reader complete: bool?
  end
end
