# frozen_string_literal: true

# rubocop:disable Style/OneClassPerFile

# Swagger Petstore - OpenAPI 3.0
# A simplified Pet Store API for integration testing.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'time'
require 'dry-struct'

# :nodoc:
module Types
  include Dry.Types()
end

# :nodoc:
module OpigenClient
  # Model classes generated from OpenAPI schemas.
  module Models
    # Model class for Pet.
    class Pet < Dry::Struct
      # Attribute mapping from ruby-style variable name to JSON key.
      ATTRIBUTE_MAP = {
        id: 'id',
        name: 'name',
        category: 'category',
        photo_urls: 'photoUrls',
        tags: 'tags',
        status: 'status'
      }.freeze

      # Inverse mapping from JSON key to ruby attribute name.
      JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

      # Attribute type mapping.
      OPENAPI_TYPES = {
        id: 'Integer',
        name: 'String',
        category: 'Category',
        photo_urls: 'Array<String>',
        tags: 'Array<Tag>',
        status: 'String'
      }.freeze

      # Transform incoming hash keys from JSON format to Ruby attribute names.
      transform_keys do |key|
        JSON_KEY_MAP[key.to_s] || key.to_sym
      end

      attribute :id, Types::Any.optional.meta(omittable: true)
      attribute :name, Types::Any
      attribute :category, Types::Any.optional.meta(omittable: true)
      attribute :photo_urls, Types::Any
      attribute :tags, Types::Any.optional.meta(omittable: true)
      attribute :status, Types::Any.optional.meta(omittable: true)
    end
  end
end
# rubocop:enable Style/OneClassPerFile
