/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { z } from 'zod';

export const ModelApiResponseSchema = z.object({
    'code': z.number().optional(),
    'type': z.string().optional(),
    'message': z.string().optional(),
}).passthrough();

export type ModelApiResponse = z.infer<typeof ModelApiResponseSchema>;

export function instanceOfModelApiResponse(value: object): value is ModelApiResponse {
    return true;
}

export function ModelApiResponseFromJSON(json: any): ModelApiResponse {
    return ModelApiResponseFromJSONTyped(json, false);
}

export function ModelApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApiResponse {
    if (json == null) {
        return json;
    }
    return ModelApiResponseSchema.parse(json);
}

export function ModelApiResponseToJSON(json: any): ModelApiResponse {
    return ModelApiResponseToJSONTyped(json, false);
}

export function ModelApiResponseToJSONTyped(value?: ModelApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return value;
}
