/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { z } from 'zod';
import { CategorySchema } from './category.js';
import { TagSchema } from './tag.js';

export const PetSchema = z.object({
    'id': z.number().optional(),
    'name': z.string(),
    'category': z.lazy(() => CategorySchema).optional(),
    'photoUrls': z.array(z.string()),
    'tags': z.array(z.lazy(() => TagSchema)).optional(),
    'status': z.string().optional(),
}).passthrough();

export type Pet = z.infer<typeof PetSchema>;

/**
 * @export
 */
export const PetStatusEnum = {
    Available: 'available',
    Pending: 'pending',
    Sold: 'sold',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type PetStatusEnum = typeof PetStatusEnum[keyof typeof PetStatusEnum];

export function instanceOfPet(value: object): value is Pet {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('photoUrls' in value) || value['photoUrls'] === undefined) return false;
    return true;
}

export function PetFromJSON(json: any): Pet {
    return PetFromJSONTyped(json, false);
}

export function PetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pet {
    if (json == null) {
        return json;
    }
    return PetSchema.parse(json);
}

export function PetToJSON(json: any): Pet {
    return PetToJSONTyped(json, false);
}

export function PetToJSONTyped(value?: Pet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return value;
}
