=begin
#Swagger Petstore - OpenAPI 3.0
#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

require 'cgi'
require 'json'

module OpigenClient::Api
  # Base class for all API classes. Provides the invoke_api method that
  # handles URL construction, header selection, body serialization, request
  # dispatch, and response deserialization.
  class BaseApi
    attr_reader :api_client, :config, :header_selector

    def initialize(api_client = OpigenClient::DefaultApiClient.new, config = OpigenClient::Configuration.default)
      @api_client = api_client
      @config = config
      @header_selector = OpigenClient::HeaderSelector.new
    end

    def invoke_api(method, path, query_params, header_params, body, accepts, content_type, return_type)
      # Build URL
      url = "#{@config.base_url}#{path}"
      query_string = build_query_string(query_params)
      url = "#{url}?#{query_string}" unless query_string.empty?

      # Select headers
      is_multipart = content_type == 'multipart/form-data'
      selected = @header_selector.select_headers(accepts, content_type || '', is_multipart)
      headers = {}
      headers['Accept'] = selected['Accept'] if selected['Accept']
      headers['Content-Type'] = selected['Content-Type'] if selected['Content-Type']

      # Apply default headers from configuration
      headers.merge!(@config.default_headers)

      # Merge custom headers
      headers.merge!(header_params)

      # Serialize body
      serialized_body = serialize_body(body, content_type)

      # Send request
      response = @api_client.send_request(method, url, headers, serialized_body)

      # Check status
      if response.status_code < 200 || response.status_code >= 300
        raise OpigenClient::ApiError.new(code: response.status_code, response_body: response.body)
      end

      # Deserialize response
      if return_type && response.body && !response.body.empty?
        OpigenClient::ObjectSerializer.deserialize(JSON.parse(response.body, symbolize_names: true), return_type)
      else
        nil
      end
    end

    protected

    def build_collection_param(param, format)
      case format
      when :csv then param.join(',')
      when :ssv then param.join(' ')
      when :tsv then param.join("\t")
      when :pipes then param.join('|')
      when :multi then param
      else param.join(',')
      end
    end

    private

    def build_query_string(query_params)
      query_params.reject { |_, v| v.nil? }.map { |k, v|
        encoded_key = CGI.escape(k.to_s)
        if v.is_a?(Array)
          v.map { |val| "#{encoded_key}=#{CGI.escape(OpigenClient::ObjectSerializer.to_query_value(val))}" }.join('&')
        else
          "#{encoded_key}=#{CGI.escape(OpigenClient::ObjectSerializer.to_query_value(v))}"
        end
      }.join('&')
    end

    def serialize_body(body, content_type)
      return nil if body.nil?

      if content_type == 'multipart/form-data'
        body.each_with_object({}) do |(k, v), hash|
          hash[k] = OpigenClient::ObjectSerializer.to_form_value(v)
        end
      elsif content_type == 'application/x-www-form-urlencoded'
        body.each_with_object({}) do |(k, v), hash|
          hash[k] = OpigenClient::ObjectSerializer.to_form_value(v)
        end.then { |sanitized| build_query_string(sanitized) }
      else
        OpigenClient::ObjectSerializer.to_json(body)
      end
    end
  end
end
