=begin
#Swagger Petstore - OpenAPI 3.0

#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'cgi'

module OpigenClient::Api
  class PetApi < BaseApi

    def initialize(api_client = OpigenClient::DefaultApiClient.new, config = OpigenClient::Configuration.default)
      super(api_client, config)
    end

    # Add a new pet to the store
    # @param pet [Pet] Create a new pet in the store
    # @param [Hash] opts the optional parameters
    # @return [Pet]
    def add_pet(pet, opts = {})
      if pet.nil?
        fail ArgumentError, "Missing the required parameter 'pet' when calling PetApi.add_pet"
      end

      path = '/pet'

      query_params = {}

      header_params = {}

      body = pet

      invoke_api(:POST, path, query_params, header_params, body,
        ['application/json'],
        'application/json',
        'Pet')
    end


    # Deletes a pet
    # @param pet_id [Integer] Pet id to delete
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_pet(pet_id, opts = {})
      if pet_id.nil?
        fail ArgumentError, "Missing the required parameter 'pet_id' when calling PetApi.delete_pet"
      end

      path = '/pet/{petId}'.sub('{' + 'petId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(pet_id)))

      query_params = {}

      header_params = {}

      body = nil

      invoke_api(:DELETE, path, query_params, header_params, body,
        [],
        'application/json',
        nil)
    end


    # Finds Pets by status
    # @param [Hash] opts the optional parameters
    # @option opts [String] :status Status values that need to be considered for filter (default to 'available')
    # @return [Array<Pet>]
    def find_pets_by_status(opts = {})

      path = '/pet/findByStatus'

      query_params = {}
      query_params[:'status'] = OpigenClient::ObjectSerializer.to_query_value(opts[:'status']) unless opts[:'status'].nil?

      header_params = {}

      body = nil

      invoke_api(:GET, path, query_params, header_params, body,
        ['application/json'],
        'application/json',
        'Array<Pet>')
    end


    # Find pet by ID
    # Returns a single pet
    # @param pet_id [Integer] ID of pet to return
    # @param [Hash] opts the optional parameters
    # @return [Pet]
    def get_pet_by_id(pet_id, opts = {})
      if pet_id.nil?
        fail ArgumentError, "Missing the required parameter 'pet_id' when calling PetApi.get_pet_by_id"
      end

      path = '/pet/{petId}'.sub('{' + 'petId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(pet_id)))

      query_params = {}

      header_params = {}

      body = nil

      invoke_api(:GET, path, query_params, header_params, body,
        ['application/json'],
        'application/json',
        'Pet')
    end


    # Update an existing pet
    # @param pet_id [Integer] ID of pet to update
    # @param pet [Pet] Pet object that needs to be updated
    # @param [Hash] opts the optional parameters
    # @return [Pet]
    def update_pet(pet_id, pet, opts = {})
      if pet_id.nil?
        fail ArgumentError, "Missing the required parameter 'pet_id' when calling PetApi.update_pet"
      end
      if pet.nil?
        fail ArgumentError, "Missing the required parameter 'pet' when calling PetApi.update_pet"
      end

      path = '/pet/{petId}'.sub('{' + 'petId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(pet_id)))

      query_params = {}

      header_params = {}

      body = pet

      invoke_api(:PUT, path, query_params, header_params, body,
        ['application/json'],
        'application/json',
        'Pet')
    end
  end
end
