module OpigenClient::Api
  class PetApi < BaseApi
    def initialize: (?ApiClient? api_client, ?Configuration config) -> void
    def add_pet: (Pet pet) -> untyped
    def delete_pet: (Integer pet_id) -> untyped
    def find_pets_by_status: (?Hash[Symbol, untyped] opts) -> untyped
    def get_pet_by_id: (Integer pet_id) -> untyped
    def update_pet: (Integer pet_id, Pet pet) -> untyped
  end
end
