=begin
#Swagger Petstore - OpenAPI 3.0

#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

require 'cgi'

module OpigenClient::Api
  class PetApi < OpigenClient::BaseApi

  def initialize(config = OpigenClient::Configuration.default)
    super(config)
  end
    # Add a new pet to the store
    # @param pet [Pet] Create a new pet in the store
    # @param [Hash] opts the optional parameters
    # @return [Pet]
    def add_pet(pet, opts = {})
      # verify the required parameter 'pet' is set
      if config.client_side_validation && pet.nil?
      fail ArgumentError, "Missing the required parameter 'pet' when calling Api::PetApi.add_pet"
      end
    # resource path
    local_var_path = '/pet'

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = select_header_content_type(['application/json'])
      if !content_type.nil?
      header_params['Content-Type'] = content_type
      end

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body] || pet

    # return_type
    return_type = opts[:debug_return_type] || 'Pet'

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:POST, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end

    # Deletes a pet
    # @param pet_id [Integer] Pet id to delete
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_pet(pet_id, opts = {})
      # verify the required parameter 'pet_id' is set
      if config.client_side_validation && pet_id.nil?
      fail ArgumentError, "Missing the required parameter 'pet_id' when calling Api::PetApi.delete_pet"
      end
    # resource path
    local_var_path = '/pet/{petId}'.sub('{' + 'petId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(pet_id)).gsub('%2F', '/'))

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body]

    # return_type
    return_type = opts[:debug_return_type]

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:DELETE, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end

    # Finds Pets by status
    # @param [Hash] opts the optional parameters
    # @option opts [String] :status Status values that need to be considered for filter (default to 'available')
    # @return [Array<Pet>]
    def find_pets_by_status(opts = {})
        allowable_values = ["available", "pending", "sold"]
        if config.client_side_validation && opts[:'status'] && !allowable_values.include?(opts[:'status'])
        fail ArgumentError, "invalid value for \"status\", must be one of #{allowable_values}"
        end
    # resource path
    local_var_path = '/pet/findByStatus'

    # query parameters
    query_params = opts[:query_params] || {}
      query_params[:'status'] = OpigenClient::ObjectSerializer.to_query_value(opts[:'status']) if !opts[:'status'].nil?

    # header parameters
    header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = select_header_accept(['application/json']) unless header_params['Accept']

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body]

    # return_type
    return_type = opts[:debug_return_type] || 'Array<Pet>'

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:GET, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end

    # Find pet by ID
    # Returns a single pet
    # @param pet_id [Integer] ID of pet to return
    # @param [Hash] opts the optional parameters
    # @return [Pet]
    def get_pet_by_id(pet_id, opts = {})
      # verify the required parameter 'pet_id' is set
      if config.client_side_validation && pet_id.nil?
      fail ArgumentError, "Missing the required parameter 'pet_id' when calling Api::PetApi.get_pet_by_id"
      end
    # resource path
    local_var_path = '/pet/{petId}'.sub('{' + 'petId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(pet_id)).gsub('%2F', '/'))

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = select_header_accept(['application/json']) unless header_params['Accept']

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body]

    # return_type
    return_type = opts[:debug_return_type] || 'Pet'

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:GET, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end

    # Update an existing pet
    # @param pet_id [Integer] ID of pet to update
    # @param pet [Pet] Pet object that needs to be updated
    # @param [Hash] opts the optional parameters
    # @return [Pet]
    def update_pet(pet_id, pet, opts = {})
      # verify the required parameter 'pet_id' is set
      if config.client_side_validation && pet_id.nil?
      fail ArgumentError, "Missing the required parameter 'pet_id' when calling Api::PetApi.update_pet"
      end
      # verify the required parameter 'pet' is set
      if config.client_side_validation && pet.nil?
      fail ArgumentError, "Missing the required parameter 'pet' when calling Api::PetApi.update_pet"
      end
    # resource path
    local_var_path = '/pet/{petId}'.sub('{' + 'petId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(pet_id)).gsub('%2F', '/'))

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = select_header_content_type(['application/json'])
      if !content_type.nil?
      header_params['Content-Type'] = content_type
      end

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body] || pet

    # return_type
    return_type = opts[:debug_return_type] || 'Pet'

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:PUT, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end
  end
end
