=begin
#Swagger Petstore - OpenAPI 3.0

#A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
=end

require 'cgi'

module OpigenClient::Api
  class StoreApi < OpigenClient::BaseApi

  def initialize(config = OpigenClient::Configuration.default)
    super(config)
  end
    # Delete purchase order by ID
    # @param order_id [Integer] ID of the order to delete
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_order(order_id, opts = {})
      # verify the required parameter 'order_id' is set
      if config.client_side_validation && order_id.nil?
      fail ArgumentError, "Missing the required parameter 'order_id' when calling Api::StoreApi.delete_order"
      end
    # resource path
    local_var_path = '/store/order/{orderId}'.sub('{' + 'orderId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(order_id)).gsub('%2F', '/'))

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body]

    # return_type
    return_type = opts[:debug_return_type]

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:DELETE, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end

    # Returns pet inventories by status
    # @param [Hash] opts the optional parameters
    # @return [Hash<String, Integer>]
    def get_inventory(opts = {})
    # resource path
    local_var_path = '/store/inventory'

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = select_header_accept(['application/json']) unless header_params['Accept']

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body]

    # return_type
    return_type = opts[:debug_return_type] || 'Hash<String, Integer>'

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:GET, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end

    # Find purchase order by ID
    # @param order_id [Integer] ID of order to return
    # @param [Hash] opts the optional parameters
    # @return [Order]
    def get_order_by_id(order_id, opts = {})
      # verify the required parameter 'order_id' is set
      if config.client_side_validation && order_id.nil?
      fail ArgumentError, "Missing the required parameter 'order_id' when calling Api::StoreApi.get_order_by_id"
      end
    # resource path
    local_var_path = '/store/order/{orderId}'.sub('{' + 'orderId' + '}', CGI.escape(OpigenClient::ObjectSerializer.to_path_value(order_id)).gsub('%2F', '/'))

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = select_header_accept(['application/json']) unless header_params['Accept']

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body]

    # return_type
    return_type = opts[:debug_return_type] || 'Order'

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:GET, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end

    # Place an order for a pet
    # @param [Hash] opts the optional parameters
    # @option opts [Order] :order
    # @return [Order]
    def place_order(opts = {})
    # resource path
    local_var_path = '/store/order'

    # query parameters
    query_params = opts[:query_params] || {}

    # header parameters
    header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = select_header_content_type(['application/json'])
      if !content_type.nil?
      header_params['Content-Type'] = content_type
      end

    # form parameters
    form_params = opts[:form_params] || {}

    # http body (model)
    body = opts[:debug_body] || opts[:'order']

    # return_type
    return_type = opts[:debug_return_type] || 'Order'

    # auth_names
    auth_names = opts[:debug_auth_names] || []

    call_api(:POST, local_var_path,
      header_params: header_params,
      query_params: query_params,
      form_params: form_params,
      body: body,
      auth_names: auth_names,
      return_type: return_type
    )
    end
  end
end
