/**
 * Swagger Petstore - OpenAPI 3.0
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { ApiResponse } from './ApiResponse.js';

/**
 * Interface for API HTTP transport.
 *
 * Implementations handle the actual HTTP request/response cycle.
 * The default implementation uses the Fetch API.
 */
export interface ApiClient {
  /**
   * Send an HTTP request and return the response.
   *
   * @param method HTTP method (GET, POST, PUT, DELETE, etc.)
   * @param url Fully qualified URL
   * @param headers HTTP headers
   * @param body Request body (serialized JSON string, or null)
   * @returns ApiResponse containing status code, body, and headers
   */
  sendRequest(
    method: string,
    url: string,
    headers: Record<string, string>,
    body: string | null
  ): Promise<ApiResponse>;
}
