/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { ApiClient } from './ApiClient.js';
import type { ApiResponse } from './ApiResponse.js';

/**
 * Default implementation of ApiClient using the Fetch API.
 */
export class DefaultApiClient implements ApiClient {
  async sendRequest(
    method: string,
    url: string,
    headers: Record<string, string>,
    body: string | null
  ): Promise<ApiResponse> {
    const response = await fetch(url, {
      method,
      headers,
      body: body ?? undefined,
    });

    const responseBody = await response.text();
    const responseHeaders: Record<string, string> = {};
    response.headers.forEach((value, key) => {
      responseHeaders[key] = value;
    });

    return {
      statusCode: response.status,
      body: responseBody,
      headers: responseHeaders,
    };
  }
}
