<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Auth;

/**
 * Interface for providing authentication credentials to the API client.
 * Implementations supply the API host URL and authorization headers.
 *
 * @category Interface
 * @package  PetstoreClient
 */
interface Authenticator
{
    /**
     * Returns the base URL of the API.
     *
     * @return string
     */
    public function getHost(): string;

    /**
     * Returns the authentication headers to include in every request.
     *
     * @return array<string, string>
     */
    public function getAuthHeaders(): array;
}
