.PHONY: all get test analyze format docs clean

all: get

get:
	dart pub get

test:
	dart test

analyze:
	dart analyze

format:
	dart format .

docs:
	dart doc

clean:
	rm -rf .dart_tool/
	rm -rf build/
	rm -rf doc/
