# frozen_string_literal: true

# Swagger Petstore - OpenAPI 3.0
# A simplified Pet Store API for integration testing.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
module OpigenClient
  # Wraps an HTTP response with status code, body, and headers.
  class ApiResponse
    attr_reader :status_code, :body, :headers

    def initialize(status_code:, body:, headers:)
      @status_code = status_code
      @body = body
      @headers = headers
    end
  end
end
