<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Auth\OAuth;

use PetstoreClient\Auth\BaseAuthenticator;

/**
 * Authenticator for the OAuth2 Implicit flow.
 */
final class OAuth2ImplicitAuthenticator extends BaseAuthenticator
{
    private readonly string $host;
    private readonly string $authorizationUrl;
    /** @var string[] */
    private readonly array $scopes;
    private ?string $accessToken = null;

    /** @param string[] $scopes */
    public function __construct(string $host, string $authorizationUrl, array $scopes)
    {
        $this->host = $host;
        $this->authorizationUrl = $authorizationUrl;
        $this->scopes = $scopes;
    }

    public function buildAuthorizationUrl(?string $state = null): string
    {
        $params = ['response_type' => 'token'];
        if ($this->scopes !== []) {
            $params['scope'] = implode(' ', $this->scopes);
        }
        if ($state !== null) {
            $params['state'] = $state;
        }
        return $this->authorizationUrl . '?' . http_build_query($params);
    }

    public function setAccessToken(string $token): void
    {
        $this->accessToken = $token;
    }

    public function getHost(): string
    {
        return $this->host;
    }

    /** @return array<string, string> */
    public function getAuthHeaders(): array
    {
        if ($this->accessToken === null) {
            throw new \RuntimeException('Must call setAccessToken() before making API requests');
        }
        return ['Authorization' => 'Bearer ' . $this->accessToken];
    }
}
