<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Auth\OAuth;

use PetstoreClient\Auth\BaseAuthenticator;

/**
 * Authenticator for OpenID Connect. Fetches the discovery document and
 * delegates to an OAuth2 Authorization Code authenticator.
 */
final class OpenIdConnectAuthenticator extends BaseAuthenticator
{
    private readonly string $host;
    private readonly string $openIdConnectUrl;
    private readonly string $clientId;
    private readonly string $clientSecret;
    private readonly string $redirectUri;
    /** @var string[] */
    private readonly array $scopes;
    private ?OAuth2AuthorizationCodeAuthenticator $delegate = null;

    /** @param string[] $scopes */
    public function __construct(
        string $host,
        string $openIdConnectUrl,
        string $clientId,
        string $clientSecret,
        string $redirectUri,
        array $scopes
    ) {
        $this->host = $host;
        $this->openIdConnectUrl = $openIdConnectUrl;
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
        $this->redirectUri = $redirectUri;
        $this->scopes = $scopes;
    }

    private function getDelegate(): OAuth2AuthorizationCodeAuthenticator
    {
        if (!$this->delegate instanceof OAuth2AuthorizationCodeAuthenticator) {
            $response = file_get_contents($this->openIdConnectUrl);
            if ($response === false) {
                throw new \RuntimeException('Failed to fetch OpenID Connect discovery document');
            }
            /** @var array{authorization_endpoint: string, token_endpoint: string} $discovery */
            $discovery = json_decode($response, true);
            $this->delegate = new OAuth2AuthorizationCodeAuthenticator(
                $this->host,
                $this->clientId,
                $this->clientSecret,
                $discovery['authorization_endpoint'],
                $discovery['token_endpoint'],
                $this->redirectUri,
                $this->scopes
            );
        }
        return $this->delegate;
    }

    public function buildAuthorizationUrl(?string $state = null): string
    {
        return $this->getDelegate()->buildAuthorizationUrl($state);
    }

    public function exchangeCode(string $code): void
    {
        $this->getDelegate()->exchangeCode($code);
    }

    public function getHost(): string
    {
        return $this->host;
    }

    /** @return array<string, string> */
    public function getAuthHeaders(): array
    {
        return $this->getDelegate()->getAuthHeaders();
    }
}
