//
// The version of the OpenAPI document: 
//
// Generated by: https://openapi-generator.tech

package org.openapitools.auth;

public final class BearerAuthenticator extends BearerAuthenticator {
    public BearerAuthenticator(String host, String token) {
        super(host, token);
    }
}
