//
// The version of the OpenAPI document: 
//
// Generated by: https://openapi-generator.tech

package org.openapitools.auth;

public final class HeaderKeyAuthenticator extends ApiKeyAuthenticator {
    public HeaderKeyAuthenticator(String host, String apiKey) {
        super(host, "X-Api-Key", apiKey, ApiKeyLocation.HEADER);
    }
}
