//
// The version of the OpenAPI document: 
//
// Generated by: https://openapi-generator.tech

package org.openapitools.auth;

public final class K1Authenticator extends ApiKeyAuthenticator {
    public K1Authenticator(String host, String apiKey) {
        super(host, "X-Token", apiKey, ApiKeyLocation.HEADER);
    }
}
