//
// The version of the OpenAPI document: 
//
// Generated by: https://openapi-generator.tech

package org.openapitools.auth;

public final class K2Authenticator extends ApiKeyAuthenticator {
    public K2Authenticator(String host, String apiKey) {
        super(host, "x-token", apiKey, ApiKeyLocation.HEADER);
    }
}
