//
// The version of the OpenAPI document: 
//
// Generated by: https://openapi-generator.tech

package org.openapitools.auth;

public final class QueryKeyAuthenticator extends ApiKeyAuthenticator {
    public QueryKeyAuthenticator(String host, String apiKey) {
        super(host, "api_key", apiKey, ApiKeyLocation.QUERY);
    }
}
