/*
 * Swagger Petstore - OpenAPI 3.0
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.petstore;

import java.util.Map;

/**
 * Interface for API HTTP transport.
 *
 * <p>Implementations handle the actual HTTP request/response cycle.
 * The default implementation uses Apache HttpClient 5.</p>
 */
@javax.annotation.Generated(value = "io.github.mridang.codegen.generators.java.BetterJavaCodegen", date = "2026-03-04T21:45:53.747469+11:00[Australia/Sydney]", comments = "Generator version: 7.14.0")
public interface ApiClient {

    /**
     * Send an HTTP request and return the response.
     *
     * @param method  HTTP method (GET, POST, PUT, DELETE, etc.)
     * @param url     Fully qualified URL
     * @param headers HTTP headers
     * @param body    Request body (serialized JSON string, or null)
     * @return ApiResponse containing status code, body, and headers
     * @throws ApiException if the request fails
     */
    ApiResponse sendRequest(String method, String url, Map<String, String> headers, String body) throws ApiException;

    /**
     * Get the base path for API requests.
     *
     * @return Base URL (e.g. "http://localhost/api/v3")
     */
    String getBasePath();
}
