/*
 * Swagger Petstore - OpenAPI 3.0
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.petstore;

import java.util.HashMap;
import java.util.Map;

/**
 * Configuration for API clients.
 *
 * <p>Holds settings that apply to all API requests such as the base URL,
 * default headers, TLS options, proxy, timeout, and retry policy.</p>
 */
@javax.annotation.Generated(value = "io.github.mridang.codegen.generators.java.BetterJavaCodegen", date = "2026-03-04T22:28:53.916353+11:00[Australia/Sydney]", comments = "Generator version: 7.14.0")
public class Configuration {

    private static volatile Configuration defaultInstance;

    /**
     * Base URL for all API requests.
     */
    private String baseUrl = "/api/v3";

    /**
     * Headers to include in every API request. Use this for authentication
     * (e.g. Authorization header) and other custom headers.
     */
    private final Map<String, String> defaultHeaders = new HashMap<>();

    /**
     * Enable debug logging of HTTP requests and responses.
     */
    private boolean debug = false;

    /**
     * Enable SSL/TLS certificate verification.
     */
    private boolean verifySsl = true;

    /**
     * Path to a CA certificate file for SSL/TLS verification.
     */
    private String sslCaCert = null;

    /**
     * Path to a client certificate file for mutual TLS authentication.
     */
    private String certFile = null;

    /**
     * Path to a client private key file for mutual TLS authentication.
     */
    private String keyFile = null;

    /**
     * Proxy URL for all API requests.
     */
    private String proxy = null;

    /**
     * Request timeout in seconds. null means no timeout.
     */
    private Integer timeout = null;

    /**
     * Number of retry attempts for failed requests. null means no retries.
     */
    private Integer retries = null;

    /**
     * Return the default configuration instance, creating it lazily if needed.
     *
     * @return the default configuration
     */
    public static Configuration getDefault() {
        if (defaultInstance == null) {
            synchronized (Configuration.class) {
                if (defaultInstance == null) {
                    defaultInstance = new Configuration();
                }
            }
        }
        return defaultInstance;
    }

    /**
     * Set the default configuration instance.
     *
     * @param configuration the configuration to use as default
     */
    public static void setDefault(Configuration configuration) {
        defaultInstance = configuration;
    }

    public String getBaseUrl() {
        return baseUrl;
    }

    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl;
    }

    public Map<String, String> getDefaultHeaders() {
        return defaultHeaders;
    }

    public boolean isDebug() {
        return debug;
    }

    public void setDebug(boolean debug) {
        this.debug = debug;
    }

    public boolean isVerifySsl() {
        return verifySsl;
    }

    public void setVerifySsl(boolean verifySsl) {
        this.verifySsl = verifySsl;
    }

    public String getSslCaCert() {
        return sslCaCert;
    }

    public void setSslCaCert(String sslCaCert) {
        this.sslCaCert = sslCaCert;
    }

    public String getCertFile() {
        return certFile;
    }

    public void setCertFile(String certFile) {
        this.certFile = certFile;
    }

    public String getKeyFile() {
        return keyFile;
    }

    public void setKeyFile(String keyFile) {
        this.keyFile = keyFile;
    }

    public String getProxy() {
        return proxy;
    }

    public void setProxy(String proxy) {
        this.proxy = proxy;
    }

    public Integer getTimeout() {
        return timeout;
    }

    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    public Integer getRetries() {
        return retries;
    }

    public void setRetries(Integer retries) {
        this.retries = retries;
    }
}
