/*
 * Swagger Petstore - OpenAPI 3.0
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.petstore;

import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.core5.http.ContentType;
import org.apache.hc.core5.http.Header;
import org.apache.hc.core5.http.ParseException;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.apache.hc.core5.http.io.entity.StringEntity;
import org.apache.hc.core5.http.io.support.ClassicRequestBuilder;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

/**
 * Default implementation of {@link ApiClient} using Apache HttpClient 5.
 */
@javax.annotation.Generated(value = "io.github.mridang.codegen.generators.java.BetterJavaCodegen", date = "2026-03-04T20:27:25.232612+11:00[Australia/Sydney]", comments = "Generator version: 7.14.0")
public class DefaultApiClient implements ApiClient {

    private String basePath;
    private final CloseableHttpClient httpClient;

    public DefaultApiClient() {
        this("/api/v3");
    }

    public DefaultApiClient(String basePath) {
        this.basePath = basePath;
        this.httpClient = HttpClients.createDefault();
    }

    public DefaultApiClient(String basePath, CloseableHttpClient httpClient) {
        this.basePath = basePath;
        this.httpClient = httpClient;
    }

    @Override
    public String getBasePath() {
        return basePath;
    }

    public void setBasePath(String basePath) {
        this.basePath = basePath;
    }

    @Override
    public ApiResponse sendRequest(String method, String url, Map<String, String> headers, String body) throws ApiException {
        ClassicRequestBuilder builder = ClassicRequestBuilder.create(method).setUri(url);

        for (Map.Entry<String, String> header : headers.entrySet()) {
            builder.addHeader(header.getKey(), header.getValue());
        }

        if (body != null) {
            builder.setEntity(new StringEntity(body, ContentType.APPLICATION_JSON.withCharset(StandardCharsets.UTF_8)));
        }

        try (CloseableHttpResponse response = httpClient.execute(builder.build())) {
            int statusCode = response.getCode();
            String responseBody = response.getEntity() != null
                ? EntityUtils.toString(response.getEntity())
                : "";
            Map<String, String> responseHeaders = new HashMap<>();
            for (Header h : response.getHeaders()) {
                responseHeaders.put(h.getName(), h.getValue());
            }
            return new ApiResponse(statusCode, responseBody != null ? responseBody : "", responseHeaders);
        } catch (IOException | ParseException e) {
            throw new ApiException(e);
        }
    }
}
