<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient;

/**
 * ApiResponse Class
 *
 * @category Class
 * @package  PetstoreClient
 */
class ApiResponse
{
    /**
     * @param int    $statusCode HTTP status code
     * @param string $body       Response body
     * @param array  $headers    Response headers
     */
    public function __construct(
        public readonly int $statusCode,
        public readonly string $body,
        public readonly array $headers
    ) {
    }
}
