<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient;

use PetstoreClient\Auth\Authenticator;
use PetstoreClient\Api\PetApi;
use PetstoreClient\Api\StoreApi;

/**
 * Unified entry point for all API services. Takes an Authenticator
 * and exposes each API group as a typed property.
 *
 * @category Class
 * @package  PetstoreClient
 */
class Client
{
    public readonly PetApi $pet;

    public readonly StoreApi $store;

    /**
     * Creates a new client with the given authenticator.
     *
     * @param Authenticator $authenticator Provides host URL and auth headers.
     */
    public function __construct(Authenticator $authenticator)
    {
        $config = new Configuration();
        $config->setBaseUrl($authenticator->getHost());
        foreach ($authenticator->getAuthHeaders() as $key => $value) {
            $config->setDefaultHeader($key, $value);
        }
        $apiClient = new DefaultApiClient($config);
        $this->pet = new PetApi($apiClient, $config);
        $this->store = new StoreApi($apiClient, $config);
    }
}
