<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient;

/**
 * Configuration for API clients.
 *
 * Holds settings that apply to all API requests such as the base URL,
 * default headers, TLS options, proxy, timeout, and retry policy.
 *
 * This class is immutable. Use {@see Configuration::builder()} to create instances:
 *
 *     $config = Configuration::builder()
 *         ->baseUrl('https://api.example.com')
 *         ->defaultHeader('Authorization', 'Bearer token')
 *         ->verifySsl(false)
 *         ->build();
 *
 * @category Class
 * @package  PetstoreClient
 */
final class Configuration
{
    private static ?Configuration $defaultInstance = null;

    /**
     * @param string               $baseUrl        Base URL for all API requests
     * @param array<string, string> $defaultHeaders Headers to include in every API request
     * @param bool                 $debug          Enable debug logging
     * @param bool                 $verifySsl      Enable SSL/TLS certificate verification
     * @param string|null          $sslCaCert      Path to a CA certificate file
     * @param string|null          $certFile       Path to a client certificate file
     * @param string|null          $keyFile        Path to a client private key file
     * @param string|null          $proxy          Proxy URL for all API requests
     * @param int|null             $timeout        Request timeout in seconds
     * @param int|null             $retries        Number of retry attempts
     */
    public function __construct(
        public readonly string $baseUrl = '/api/v3',
        public readonly array $defaultHeaders = [],
        public readonly bool $debug = false,
        public readonly bool $verifySsl = true,
        public readonly ?string $sslCaCert = null,
        public readonly ?string $certFile = null,
        public readonly ?string $keyFile = null,
        public readonly ?string $proxy = null,
        public readonly ?int $timeout = null,
        public readonly ?int $retries = null,
    ) {
    }

    /**
     * Create a new builder for constructing Configuration instances.
     */
    public static function builder(): ConfigurationBuilder
    {
        return new ConfigurationBuilder();
    }

    /**
     * Return the default configuration instance, creating it lazily if needed.
     */
    public static function getDefaultConfiguration(): Configuration
    {
        if (!self::$defaultInstance instanceof Configuration) {
            self::$defaultInstance = new Configuration();
        }

        return self::$defaultInstance;
    }

    /**
     * Set the default configuration instance.
     */
    public static function setDefaultConfiguration(Configuration $configuration): void
    {
        self::$defaultInstance = $configuration;
    }
}
