<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient;

/**
 * Configuration for API clients.
 *
 * Holds settings that apply to all API requests such as the base URL,
 * default headers, TLS options, proxy, timeout, and retry policy.
 */
class Configuration
{
    /**
     * @var Configuration|null
     */
    private static ?Configuration $defaultInstance = null;

    /**
     * Base URL for all API requests.
     *
     * @var string
     */
    private string $baseUrl = '/api/v3';

    /**
     * Headers to include in every API request. Use this for authentication
     * (e.g. Authorization header) and other custom headers.
     *
     * @var array<string, string>
     */
    private array $defaultHeaders = [];

    /**
     * Enable debug logging of HTTP requests and responses.
     *
     * @var bool
     */
    private bool $debug = false;

    /**
     * Enable SSL/TLS certificate verification.
     *
     * @var bool
     */
    private bool $verifySsl = true;

    /**
     * Path to a CA certificate file for SSL/TLS verification.
     *
     * @var string|null
     */
    private ?string $sslCaCert = null;

    /**
     * Path to a client certificate file for mutual TLS authentication.
     *
     * @var string|null
     */
    private ?string $certFile = null;

    /**
     * Path to a client private key file for mutual TLS authentication.
     *
     * @var string|null
     */
    private ?string $keyFile = null;

    /**
     * Proxy URL for all API requests.
     *
     * @var string|null
     */
    private ?string $proxy = null;

    /**
     * Request timeout in seconds. null means no timeout.
     *
     * @var int|null
     */
    private ?int $timeout = null;

    /**
     * Number of retry attempts for failed requests. null means no retries.
     *
     * @var int|null
     */
    private ?int $retries = null;

    /**
     * Return the default configuration instance, creating it lazily if needed.
     *
     * @return Configuration
     */
    public static function getDefaultConfiguration(): Configuration
    {
        if (self::$defaultInstance === null) {
            self::$defaultInstance = new Configuration();
        }

        return self::$defaultInstance;
    }

    /**
     * Set the default configuration instance.
     *
     * @param Configuration $configuration the configuration to use as default
     */
    public static function setDefaultConfiguration(Configuration $configuration): void
    {
        self::$defaultInstance = $configuration;
    }

    /**
     * @return string
     */
    public function getBaseUrl(): string
    {
        return $this->baseUrl;
    }

    /**
     * @param string $baseUrl
     * @return $this
     */
    public function setBaseUrl(string $baseUrl): static
    {
        $this->baseUrl = $baseUrl;
        return $this;
    }

    /**
     * @return array<string, string>
     */
    public function getDefaultHeaders(): array
    {
        return $this->defaultHeaders;
    }

    /**
     * @param string $name
     * @param string $value
     * @return $this
     */
    public function setDefaultHeader(string $name, string $value): static
    {
        $this->defaultHeaders[$name] = $value;
        return $this;
    }

    /**
     * @return bool
     */
    public function isDebug(): bool
    {
        return $this->debug;
    }

    /**
     * @param bool $debug
     * @return $this
     */
    public function setDebug(bool $debug): static
    {
        $this->debug = $debug;
        return $this;
    }

    /**
     * @return bool
     */
    public function isVerifySsl(): bool
    {
        return $this->verifySsl;
    }

    /**
     * @param bool $verifySsl
     * @return $this
     */
    public function setVerifySsl(bool $verifySsl): static
    {
        $this->verifySsl = $verifySsl;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getSslCaCert(): ?string
    {
        return $this->sslCaCert;
    }

    /**
     * @param string|null $sslCaCert
     * @return $this
     */
    public function setSslCaCert(?string $sslCaCert): static
    {
        $this->sslCaCert = $sslCaCert;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getCertFile(): ?string
    {
        return $this->certFile;
    }

    /**
     * @param string|null $certFile
     * @return $this
     */
    public function setCertFile(?string $certFile): static
    {
        $this->certFile = $certFile;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getKeyFile(): ?string
    {
        return $this->keyFile;
    }

    /**
     * @param string|null $keyFile
     * @return $this
     */
    public function setKeyFile(?string $keyFile): static
    {
        $this->keyFile = $keyFile;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getProxy(): ?string
    {
        return $this->proxy;
    }

    /**
     * @param string|null $proxy
     * @return $this
     */
    public function setProxy(?string $proxy): static
    {
        $this->proxy = $proxy;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getTimeout(): ?int
    {
        return $this->timeout;
    }

    /**
     * @param int|null $timeout
     * @return $this
     */
    public function setTimeout(?int $timeout): static
    {
        $this->timeout = $timeout;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getRetries(): ?int
    {
        return $this->retries;
    }

    /**
     * @param int|null $retries
     * @return $this
     */
    public function setRetries(?int $retries): static
    {
        $this->retries = $retries;
        return $this;
    }
}
