<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\GuzzleException;
use PetstoreClient\Configuration;
use RuntimeException;

/**
 * DefaultApiClient Class
 *
 * Default implementation of ApiClient using Guzzle HTTP client.
 *
 * @category Class
 * @package  PetstoreClient
 */
class DefaultApiClient implements ApiClient
{
    private ClientInterface $client;

    /**
     * @param Configuration|null   $config Configuration instance
     * @param ClientInterface|null $client Guzzle client instance
     */
    public function __construct(?Configuration $config = null, ?ClientInterface $client = null)
    {
        if ($client instanceof ClientInterface) {
            $this->client = $client;
        } else {
            $options = [
                'http_errors' => false,
            ];

            if ($config instanceof Configuration) {
                if (!$config->isVerifySsl()) {
                    $options['verify'] = false;
                } elseif ($config->getSslCaCert() !== null) {
                    $options['verify'] = $config->getSslCaCert();
                }

                if ($config->getProxy() !== null) {
                    $options['proxy'] = $config->getProxy();
                }
            }

            $this->client = new Client($options);
        }
    }

    /**
     * @param string               $method  HTTP method
     * @param string               $url     Fully qualified URL
     * @param array<string, string> $headers HTTP headers
     * @param mixed                $body    Request body
     */
    public function sendRequest(string $method, string $url, array $headers, mixed $body): ApiResponse
    {
        $options = [
            'headers' => $headers,
        ];

        if ($body !== null) {
            $options['body'] = $body;
        }

        try {
            $response = $this->client->request($method, $url, $options);
        } catch (GuzzleException $e) {
            throw new RuntimeException(
                "API Request failed: [{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                $e
            );
        }

        return new ApiResponse(
            statusCode: $response->getStatusCode(),
            body: (string) $response->getBody(),
            headers: $response->getHeaders()
        );
    }
}
