<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient;

use PetstoreClient\Configuration;
use RuntimeException;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\Mime\Part\DataPart;
use Symfony\Component\Mime\Part\Multipart\FormDataPart;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

/**
 * DefaultApiClient Class
 *
 * Default implementation of ApiClient using Symfony HTTP client.
 *
 * @category Class
 * @package  PetstoreClient
 */
class DefaultApiClient implements ApiClient
{
    private readonly HttpClientInterface $client;

    /**
     * @param Configuration|null      $config Configuration instance
     * @param HttpClientInterface|null $client Symfony HTTP client instance
     */
    public function __construct(?Configuration $config = null, ?HttpClientInterface $client = null)
    {
        if ($client instanceof HttpClientInterface) {
            $this->client = $client;
        } else {
            $options = [];

            if ($config instanceof Configuration) {
                if (!$config->verifySsl) {
                    $options['verify_peer'] = false;
                    $options['verify_host'] = false;
                } elseif ($config->sslCaCert !== null) {
                    $options['cafile'] = $config->sslCaCert;
                }

                if ($config->proxy !== null) {
                    $options['proxy'] = $config->proxy;
                }
            }

            $this->client = HttpClient::create($options);
        }
    }

    /**
     * @param string               $method  HTTP method
     * @param string               $url     Fully qualified URL
     * @param array<string, string> $headers HTTP headers
     * @param mixed                $body    Request body
     */
    public function sendRequest(string $method, string $url, array $headers, mixed $body): ApiResponse
    {
        $headers['Accept-Encoding'] ??= self::getSupportedEncodings();

        if (is_array($body)) {
            unset($headers['Content-Type']);
            $formFields = [];
            foreach ($body as $name => $value) {
                $values = is_array($value) ? $value : [$value];
                $parts = [];
                foreach ($values as $v) {
                    if (is_object($v) && !($v instanceof \SplFileObject)) {
                        $parts[] = new DataPart(
                            ObjectSerializer::serialize($v),
                            null,
                            'application/json'
                        );
                    } elseif ($v instanceof \SplFileObject) {
                        $parts[] = DataPart::fromPath($v->getRealPath());
                    } elseif (is_resource($v)) {
                        $parts[] = new DataPart(stream_get_contents($v));
                    } elseif (is_scalar($v)) {
                        $parts[] = strval($v);
                    } else {
                        $parts[] = '';
                    }
                }
                $formFields[(string) $name] = count($parts) === 1 ? $parts[0] : $parts;
            }
            $formData = new FormDataPart($formFields);
            $contentType = $formData->getPreparedHeaders()->get('Content-Type');
            if ($contentType instanceof \Symfony\Component\Mime\Header\HeaderInterface) {
                $headers['Content-Type'] = $contentType->getBodyAsString();
            }
            $options = [
                'headers' => $headers,
                'body' => $formData->bodyToIterable(),
            ];
        } else {
            $options = [
                'headers' => $headers,
            ];

            if ($body !== null) {
                $options['body'] = $body;
            }
        }

        try {
            $response = $this->client->request($method, $url, $options);

            $responseBody = $response->getContent(false);
            $responseHeaders = $response->getHeaders(false);
            $contentEncoding = $responseHeaders['content-encoding'][0] ?? '';
            $responseBody = $this->decompressBody($responseBody, $contentEncoding);

            return new ApiResponse(
                statusCode: $response->getStatusCode(),
                body: $responseBody,
                headers: $responseHeaders
            );
        } catch (TransportExceptionInterface $e) {
            throw new RuntimeException(
                "API Request failed: {$e->getMessage()}",
                0,
                $e
            );
        }
    }

    private static function getSupportedEncodings(): string
    {
        $encodings = ['gzip', 'deflate'];
        if (function_exists('brotli_uncompress')) {
            $encodings[] = 'br';
        }
        if (function_exists('zstd_uncompress')) {
            $encodings[] = 'zstd';
        }

        return implode(', ', $encodings);
    }

    private function decompressBody(string $body, string $encoding): string
    {
        if ($body === '') {
            return $body;
        }

        return match (strtolower($encoding)) {
            'gzip', 'x-gzip' => gzdecode($body) ?: $body,
            'deflate' => gzinflate($body) ?: $body,
            'br' => function_exists('brotli_uncompress')
                ? (brotli_uncompress($body) ?: $body)
                : $body,
            'zstd' => function_exists('zstd_uncompress')
                ? (zstd_uncompress($body) ?: $body)
                : $body,
            default => $body,
        };
    }
}
