.PHONY: all build test lint fmt vet clean

all: build

build:
	go build ./...

test:
	go test -v -race ./...

lint:
	golangci-lint run ./...

fmt:
	gofmt -s -w .

vet:
	go vet ./...

clean:
	go clean ./...
