module Dry
  def self.Types: () -> Module

  class Struct
    def self.attribute: (Symbol, untyped) -> void
    def self.transform_keys: () { (untyped) -> untyped } -> void
  end
end

module Types
  Any: untyped
end

module Faraday
  def self.new: (?String?) ?{ (Connection) -> void } -> Connection

  class Connection
    attr_accessor proxy: String?
    attr_accessor ssl: SSLOptions
    def run_request: (Symbol, String?, String?, Hash[String, String]?) -> Response
  end

  class SSLOptions
    attr_accessor verify: bool
    attr_accessor ca_file: String?
    attr_accessor client_cert: String?
    attr_accessor client_key: String?
  end

  class Response
    def status: () -> Integer
    def body: () -> String
    def headers: () -> Hash[String, String]
  end
end
