<?php

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

namespace PetstoreClient\Api;

use PetstoreClient\ApiClient;
use PetstoreClient\ApiException;
use PetstoreClient\ApiResponse;
use PetstoreClient\Configuration;
use PetstoreClient\DefaultApiClient;
use PetstoreClient\HeaderSelector;
use PetstoreClient\ObjectSerializer;
use GuzzleHttp\Psr7\MultipartStream;

/**
 * Base class for all API classes. Provides the invokeApi method that
 * handles URL construction, header selection, body serialization, request
 * dispatch, and response deserialization.
 *
 * @category Class
 * @package  PetstoreClient
 */
class BaseApi
{
    protected ApiClient $apiClient;

    protected Configuration $config;

    protected HeaderSelector $headerSelector;

    /**
     * @param ApiClient|null     $apiClient API client instance
     * @param Configuration|null $config    Configuration instance
     */
    public function __construct(
        ?ApiClient $apiClient = null,
        ?Configuration $config = null
    ) {
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->apiClient = $apiClient ?: new DefaultApiClient($this->config);
        $this->headerSelector = new HeaderSelector();
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Invoke an API operation.
     *
     * @param string                $method       HTTP method
     * @param string                $path         URL path (with path params already substituted)
     * @param array<string, mixed>  $queryParams  Query parameters
     * @param array<string, string> $headerParams Custom header parameters
     * @param mixed                 $body         Request body (model object or form params array)
     * @param string[]              $accepts      Acceptable response content types
     * @param string|null           $contentType  Request content type
     * @param string|null           $returnType   Return type for deserialization
     *
     * @return mixed Deserialized response or null
     * @throws ApiException
     */
    protected function invokeApi(
        string $method,
        string $path,
        array $queryParams,
        array $headerParams,
        mixed $body,
        array $accepts,
        ?string $contentType,
        ?string $returnType
    ): mixed {
        $url = $this->config->getBaseUrl() . $path;
        $query = $this->buildQuery($queryParams);
        if ($query !== '') {
            $url .= '?' . $query;
        }

        $isMultipart = $contentType === 'multipart/form-data';
        $headers = $this->headerSelector->selectHeaders($accepts, $contentType ?? '', $isMultipart);
        $headers = array_merge($headers, $this->config->getDefaultHeaders());
        $headers = array_merge($headers, $headerParams);

        $serializedBody = $this->serializeBody($body, $contentType, $isMultipart);

        $response = $this->apiClient->sendRequest($method, $url, $headers, $serializedBody);

        if ($response->statusCode < 200 || $response->statusCode >= 300) {
            throw new ApiException(
                sprintf('[%d] Error', $response->statusCode),
                $response->statusCode,
                $response->headers,
                $response->body
            );
        }

        if ($returnType !== null && trim($response->body) !== '') {
            return ObjectSerializer::deserialize($response->body, $returnType, []);
        }

        return null;
    }

    /**
     * Build a query string from an array of key value pairs.
     *
     * @param array<string, mixed> $params Query string parameters
     */
    private function buildQuery(array $params): string
    {
        if ($params === []) {
            return '';
        }

        $qs = '';
        foreach ($params as $k => $v) {
            $k = rawurlencode($k);
            if (is_array($v)) {
                foreach ($v as $vv) {
                    $qs .= $k;
                    if (is_bool($vv)) {
                        $qs .= '=' . rawurlencode($vv ? 'true' : 'false');
                    } elseif (is_scalar($vv)) {
                        $qs .= '=' . rawurlencode((string) $vv);
                    }
                    $qs .= '&';
                }
            } else {
                $qs .= $k;
                if (is_bool($v)) {
                    $qs .= '=' . rawurlencode($v ? 'true' : 'false');
                } elseif (is_scalar($v)) {
                    $qs .= '=' . rawurlencode((string) $v);
                }
                $qs .= '&';
            }
        }

        return $qs !== '' ? substr($qs, 0, -1) : '';
    }

    /**
     * Serialize the request body based on content type.
     *
     * @param mixed       $body        Request body
     * @param string|null $contentType Content type
     * @param bool        $isMultipart Whether the request is multipart
     *
     * @return mixed Serialized body
     */
    private function serializeBody(mixed $body, ?string $contentType, bool $isMultipart): mixed
    {
        if ($body === null) {
            return null;
        }

        if ($isMultipart) {
            assert(is_array($body));
            $multipartContents = [];
            /** @var array<string, mixed> $body */
            foreach ($body as $name => $value) {
                $values = is_array($value) ? $value : [$value];
                foreach ($values as $v) {
                    $multipartContents[] = [
                        'name' => (string) $name,
                        'contents' => $v,
                    ];
                }
            }
            return new MultipartStream($multipartContents);
        }

        if ($contentType === 'application/x-www-form-urlencoded') {
            assert(is_array($body));
            /** @var array<string, mixed> $body */
            return $this->buildQuery($body);
        }

        return ObjectSerializer::serialize($body);
    }
}
