<?php
/**
 * PetApi
 * PHP version 8.1
 *
 * @category Class
 * @package  PetstoreClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PetstoreClient\Api;

use PetstoreClient\ApiClient;
use PetstoreClient\ApiException;
use PetstoreClient\Configuration;
use PetstoreClient\DefaultApiClient;
use PetstoreClient\ObjectSerializer;

/**
 * PetApi Class Doc Comment
 *
 * @category Class
 * @package  PetstoreClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PetApi extends BaseApi
{
    /**
     * @param ApiClient|null     $apiClient API client instance
     * @param Configuration|null $config    Configuration instance
     */
    public function __construct(
        ?ApiClient $apiClient = null,
        ?Configuration $config = null
    ) {
        parent::__construct($apiClient, $config);
    }

    /**
     * Add a new pet to the store
     *
     * @param  \PetstoreClient\Models\Pet $pet Create a new pet in the store (required)
     *
     * @return \PetstoreClient\Models\Pet
     * @throws ApiException
     */
    public function addPet($pet)
    {
        if ($pet === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $pet when calling addPet'
            );
        }

        $path = '/pet';

        $queryParams = [];

        $headerParams = [];

        $body = $pet;

        return $this->invokeApi(
            'POST',
            $path,
            $queryParams,
            $headerParams,
            $body,
            ['application/json'],
            'application/json',
            [],
            '\PetstoreClient\Models\Pet'
        );
    }

    /**
     * Deletes a pet
     *
     * @param  int $petId Pet id to delete (required)
     *
     * @return void
     * @throws ApiException
     */
    public function deletePet($petId)
    {
        if ($petId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $petId when calling deletePet'
            );
        }

        $path = '/pet/{petId}';
        $path = str_replace(
            '{' . 'petId' . '}',
            ObjectSerializer::toPathValue($petId),
            $path
        );

        $queryParams = [];

        $headerParams = [];

        $body = null;

        return $this->invokeApi(
            'DELETE',
            $path,
            $queryParams,
            $headerParams,
            $body,
            [],
            'application/json',
            [],
            null
        );
    }

    /**
     * Finds Pets by status
     *
     * @param  string|null $status Status values that need to be considered for filter (optional, default to 'available')
     *
     * @return \PetstoreClient\Models\Pet[]
     * @throws ApiException
     */
    public function findPetsByStatus($status = 'available')
    {

        $path = '/pet/findByStatus';

        $queryParams = [];
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }

        $headerParams = [];

        $body = null;

        return $this->invokeApi(
            'GET',
            $path,
            $queryParams,
            $headerParams,
            $body,
            ['application/json'],
            'application/json',
            [],
            '\PetstoreClient\Models\Pet[]'
        );
    }

    /**
     * Find pet by ID
     *
     * @param  int $petId ID of pet to return (required)
     *
     * @return \PetstoreClient\Models\Pet
     * @throws ApiException
     */
    public function getPetById($petId)
    {
        if ($petId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $petId when calling getPetById'
            );
        }

        $path = '/pet/{petId}';
        $path = str_replace(
            '{' . 'petId' . '}',
            ObjectSerializer::toPathValue($petId),
            $path
        );

        $queryParams = [];

        $headerParams = [];

        $body = null;

        return $this->invokeApi(
            'GET',
            $path,
            $queryParams,
            $headerParams,
            $body,
            ['application/json'],
            'application/json',
            [],
            '\PetstoreClient\Models\Pet'
        );
    }

    /**
     * Update an existing pet
     *
     * @param  int $petId ID of pet to update (required)
     * @param  \PetstoreClient\Models\Pet $pet Pet object that needs to be updated (required)
     *
     * @return \PetstoreClient\Models\Pet
     * @throws ApiException
     */
    public function updatePet($petId, $pet)
    {
        if ($petId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $petId when calling updatePet'
            );
        }
        if ($pet === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $pet when calling updatePet'
            );
        }

        $path = '/pet/{petId}';
        $path = str_replace(
            '{' . 'petId' . '}',
            ObjectSerializer::toPathValue($petId),
            $path
        );

        $queryParams = [];

        $headerParams = [];

        $body = $pet;

        return $this->invokeApi(
            'PUT',
            $path,
            $queryParams,
            $headerParams,
            $body,
            ['application/json'],
            'application/json',
            [],
            '\PetstoreClient\Models\Pet'
        );
    }

}
