<?php
/**
 * StoreApi
 * PHP version 8.1
 *
 * @category Class
 * @package  PetstoreClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * A simplified Pet Store API for integration testing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PetstoreClient\Api;

use PetstoreClient\ApiClient;
use PetstoreClient\ApiException;
use PetstoreClient\BaseApi;
use PetstoreClient\Configuration;
use PetstoreClient\DefaultApiClient;
use PetstoreClient\ObjectSerializer;

/**
 * StoreApi Class Doc Comment
 *
 * @category Class
 * @package  PetstoreClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StoreApi extends BaseApi
{
    /**
     * @param ApiClient|null     $apiClient API client instance
     * @param Configuration|null $config    Configuration instance
     */
    public function __construct(
        ?ApiClient $apiClient = null,
        ?Configuration $config = null
    ) {
        parent::__construct($apiClient, $config);
    }

    /**
     * Operation deleteOrder
     *
     * Delete purchase order by ID
     *
     * @param  int $orderId ID of the order to delete (required)
     *
     * @return null
     * @throws ApiException
     */
    public function deleteOrder($orderId, )
    {
        if ($orderId === null || (is_array($orderId) && count($orderId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $orderId when calling deleteOrder'
            );
        }

        $path = '/store/order/{orderId}';
        if ($orderId !== null) {
            $path = str_replace(
                '{' . 'orderId' . '}',
                ObjectSerializer::toPathValue($orderId),
                $path
            );
        }

        $queryParams = [];

        $headerParams = [];

        $body = null;

        return $this->invokeApi(
            'DELETE',
            $path,
            $queryParams,
            $headerParams,
            $body,
            [],
            null,
            [],
            null
        );
    }

    /**
     * Operation getInventory
     *
     * Returns pet inventories by status
     *
     *
     * @return array<string,int>
     * @throws ApiException
     */
    public function getInventory()
    {

        $path = '/store/inventory';

        $queryParams = [];

        $headerParams = [];

        $body = null;

        return $this->invokeApi(
            'GET',
            $path,
            $queryParams,
            $headerParams,
            $body,
            ['application/json', ],
            null,
            [],
            'array<string,int>'
        );
    }

    /**
     * Operation getOrderById
     *
     * Find purchase order by ID
     *
     * @param  int $orderId ID of order to return (required)
     *
     * @return \PetstoreClient\Model\Order
     * @throws ApiException
     */
    public function getOrderById($orderId, )
    {
        if ($orderId === null || (is_array($orderId) && count($orderId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $orderId when calling getOrderById'
            );
        }

        $path = '/store/order/{orderId}';
        if ($orderId !== null) {
            $path = str_replace(
                '{' . 'orderId' . '}',
                ObjectSerializer::toPathValue($orderId),
                $path
            );
        }

        $queryParams = [];

        $headerParams = [];

        $body = null;

        return $this->invokeApi(
            'GET',
            $path,
            $queryParams,
            $headerParams,
            $body,
            ['application/json', ],
            null,
            [],
            '\PetstoreClient\Model\Order'
        );
    }

    /**
     * Operation placeOrder
     *
     * Place an order for a pet
     *
     * @param  \PetstoreClient\Model\Order|null $order (optional)
     *
     * @return \PetstoreClient\Model\Order
     * @throws ApiException
     */
    public function placeOrder($order = null, )
    {

        $path = '/store/order';

        $queryParams = [];

        $headerParams = [];

        $body = $order;

        return $this->invokeApi(
            'POST',
            $path,
            $queryParams,
            $headerParams,
            $body,
            ['application/json', ],
            'application/json',
            [],
            '\PetstoreClient\Model\Order'
        );
    }

}
