# frozen_string_literal: true

# Swagger Petstore - OpenAPI 3.0
# A simplified Pet Store API for integration testing.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

# Dependencies
require 'dry-struct'
require 'dry-types'

# Common files
require 'petstore_client/api_error'
require 'petstore_client/version'
require 'petstore_client/configuration'
require 'petstore_client/header_selector'
require 'petstore_client/object_serializer'
require 'petstore_client/trace_context_util'
require 'petstore_client/api_response'
require 'petstore_client/api_client'
require 'petstore_client/default_api_client'
require 'petstore_client/api/base_api'
require 'petstore_client/auth/authenticator'
require 'petstore_client/auth/basic_authenticator'
require 'petstore_client/auth/bearer_authenticator'
require 'petstore_client/auth/api_key_authenticator'
require 'petstore_client/auth/oauth/oauth2_token_manager'
require 'petstore_client/auth/oauth/oauth2_client_credentials_authenticator'
require 'petstore_client/auth/oauth/oauth2_password_authenticator'
require 'petstore_client/auth/oauth/oauth2_auth_code_authenticator'
require 'petstore_client/auth/oauth/oauth2_implicit_authenticator'
require 'petstore_client/auth/oauth/openid_connect_authenticator'
require 'petstore_client/client'

# Models
require 'petstore_client/models/api_response'
require 'petstore_client/models/category'
require 'petstore_client/models/dry_food'
require 'petstore_client/models/order'
require 'petstore_client/models/pet'
require 'petstore_client/models/pet_food'
require 'petstore_client/models/pet_passport'
require 'petstore_client/models/photo'
require 'petstore_client/models/photo_metadata'
require 'petstore_client/models/photo_metadata_location'
require 'petstore_client/models/set_pet_avatar_request'
require 'petstore_client/models/set_pet_avatar_thumbnail_request'
require 'petstore_client/models/tag'
require 'petstore_client/models/wet_food'

# APIs
require 'petstore_client/api/pet_api'
require 'petstore_client/api/store_api'

# :nodoc:
module PetstoreClient
  class << self
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
