name: Lint Code (Checkstyle and Spotbugs)

on: push

permissions:
  contents: write

defaults:
  run:
    working-directory: ./

jobs:
  code-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'corretto'
            cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Checks
        run: gradle check --no-daemon
