name: Lint Code (Checkstyle and Spotbugs)

on: push

permissions:
  contents: write

defaults:
  run:
    working-directory: ./

jobs:
  code-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Install Dependencies
        run: mvn --batch-mode --show-version dependency:go-offline

      - name: Run Formatter
        run: mvn compile spotbugs:check
