name: Run Tests (Jest)

on: push

permissions:
  contents: write

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ./docker_images
          key: ${{ runner.os }}-docker-${{ hashFiles('docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-

#      - name: Docker pull
#        run: |
#          IMAGES_DIR="./docker_images"
#          COMBINED_IMAGES_TAR="$IMAGES_DIR/combined_images.tar"
#
#          if [ -f "$COMBINED_IMAGES_TAR" ]; then
#          docker image load -i "$COMBINED_IMAGES_TAR"
#          else
#          mkdir -p "$IMAGES_DIR"
#          IMAGES=$(docker compose config --images)
#          docker pull $IMAGES
#          docker image save -o "$COMBINED_IMAGES_TAR" $IMAGES
#          fi

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Install Dependencies
        run: mvn --batch-mode --show-version dependency:go-offline

      - name: Run Junit
        run: mvn verify --batch-mode
