"""
Swagger Petstore - OpenAPI 3.0

A simplified Pet Store API for integration testing.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = '1.0.0'

# Define package exports
__all__ = [
    'PetApi',
    'StoreApi',
    'Authenticator',
    'Client',
    'ApiClient',
    'Configuration',
    'OpenApiException',
    'ApiTypeError',
    'ApiValueError',
    'ApiKeyError',
    'ApiAttributeError',
    'ApiException',
    'ApiResponse',
    'Category',
    'DryFood',
    'Order',
    'Pet',
    'PetFood',
    'PetPassport',
    'Photo',
    'PhotoMetadata',
    'PhotoMetadataLocation',
    'SetPetAvatarRequest',
    'SetPetAvatarThumbnailRequest',
    'Tag',
    'WetFood',
]

# import apis into sdk package
from petstore_client.api.pet_api import PetApi as PetApi
from petstore_client.api.store_api import StoreApi as StoreApi

# import ApiClient
from petstore_client.api_client import ApiClient as ApiClient
from petstore_client.auth.authenticator import Authenticator as Authenticator
from petstore_client.client import Client as Client
from petstore_client.configuration import Configuration as Configuration
from petstore_client.exceptions import OpenApiException as OpenApiException
from petstore_client.exceptions import ApiTypeError as ApiTypeError
from petstore_client.exceptions import ApiValueError as ApiValueError
from petstore_client.exceptions import ApiKeyError as ApiKeyError
from petstore_client.exceptions import ApiAttributeError as ApiAttributeError
from petstore_client.exceptions import ApiException as ApiException

# import models into sdk package
from petstore_client.models.api_response import (
    ApiResponse as ApiResponse,
)
from petstore_client.models.category import (
    Category as Category,
)
from petstore_client.models.dry_food import (
    DryFood as DryFood,
)
from petstore_client.models.order import (
    Order as Order,
)
from petstore_client.models.pet import (
    Pet as Pet,
)
from petstore_client.models.pet_food import (
    PetFood as PetFood,
)
from petstore_client.models.pet_passport import (
    PetPassport as PetPassport,
)
from petstore_client.models.photo import (
    Photo as Photo,
)
from petstore_client.models.photo_metadata import (
    PhotoMetadata as PhotoMetadata,
)
from petstore_client.models.photo_metadata_location import (
    PhotoMetadataLocation as PhotoMetadataLocation,
)
from petstore_client.models.set_pet_avatar_request import (
    SetPetAvatarRequest as SetPetAvatarRequest,
)
from petstore_client.models.set_pet_avatar_thumbnail_request import (
    SetPetAvatarThumbnailRequest as SetPetAvatarThumbnailRequest,
)
from petstore_client.models.tag import (
    Tag as Tag,
)
from petstore_client.models.wet_food import (
    WetFood as WetFood,
)
